/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hello_bangladesh;

import java.awt.Color;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Asus
 */
public class emergency extends javax.swing.JFrame {

    ImageIcon ii,icon;
   
    public emergency() {
        initComponents();
        
        pack();
         icon = new ImageIcon(getClass().getResource("image\\bangladesh map_316px.png"));
         setIconImage(icon.getImage()); // set java frame icon
         setLocationRelativeTo(null);
        setBackground(new Color(0,0,0,0)); 
        jPanelemergency.setBackground(new Color(53,59,72,230));
        //bangladesh.setBackground(new Color(0,0,0,55));
        jPanelmenu.setVisible(false);
        //jPanelmenu.setBackground(new Color(53,59,72,100));
        jPanelpersonal.setVisible(false);
        jPanelpersonal.setBackground(new Color(53,59,72,100));
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelpersonal = new javax.swing.JPanel();
        jLabellogout = new javax.swing.JLabel();
        jLabelsettings = new javax.swing.JLabel();
        jLabelhelp = new javax.swing.JLabel();
        jPanelmenu = new javax.swing.JPanel();
        jLabelhome = new javax.swing.JLabel();
        jLabelemergencymenu = new javax.swing.JLabel();
        jLabelreportmenu = new javax.swing.JLabel();
        jLabelgovinfomenu = new javax.swing.JLabel();
        jLabelfeedbackmenu = new javax.swing.JLabel();
        jLabelsettingsmenu = new javax.swing.JLabel();
        jLabelsupportmenu = new javax.swing.JLabel();
        jLabellogoutmenu = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabelback = new javax.swing.JLabel();
        jPanelemergency = new javax.swing.JPanel();
        jLabelemeregency = new javax.swing.JLabel();
        jLabeluser = new javax.swing.JLabel();
        jLabelClose = new javax.swing.JLabel();
        jLabeMin = new javax.swing.JLabel();
        jLabelmenu = new javax.swing.JLabel();
        jLabelpolice = new javax.swing.JLabel();
        jLabelfireservice = new javax.swing.JLabel();
        jLabelambulaance = new javax.swing.JLabel();
        jLabelneighbours = new javax.swing.JLabel();
        jLabelelectricity = new javax.swing.JLabel();
        jLabelelwasa = new javax.swing.JLabel();
        bangladesh = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelpersonal.setBackground(new java.awt.Color(53, 59, 73));
        jPanelpersonal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabellogout.setBackground(new java.awt.Color(52, 59, 72));
        jLabellogout.setForeground(new java.awt.Color(255, 255, 255));
        jLabellogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hello_bangladesh/image/logout.png"))); // NOI18N
        jLabellogout.setText("Log Out");
        jLabellogout.setOpaque(true);
        jLabellogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabellogoutMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabellogoutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabellogoutMouseExited(evt);
            }
        });
        jPanelpersonal.add(jLabellogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 90, 20));

        jLabelsettings.setBackground(new java.awt.Color(52, 59, 72));
        jLabelsettings.setForeground(new java.awt.Color(255, 255, 255));
        jLabelsettings.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hello_bangladesh/image/settings.png"))); // NOI18N
        jLabelsettings.setText("Settings");
        jLabelsettings.setOpaque(true);
        jLabelsettings.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelsettingsMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelsettingsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelsettingsMouseExited(evt);
            }
        });
        jPanelpersonal.add(jLabelsettings, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 90, 20));

        jLabelhelp.setBackground(new java.awt.Color(52, 59, 72));
        jLabelhelp.setForeground(new java.awt.Color(255, 255, 255));
        jLabelhelp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hello_bangladesh/image/help.png"))); // NOI18N
        jLabelhelp.setText("Help");
        jLabelhelp.setOpaque(true);
        jLabelhelp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelhelpMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelhelpMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelhelpMouseExited(evt);
            }
        });
        jPanelpersonal.add(jLabelhelp, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 90, 20));

        getContentPane().add(jPanelpersonal, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 40, 90, 60));

        jPanelmenu.setBackground(new java.awt.Color(53, 59, 73));
        jPanelmenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelhome.setBackground(new java.awt.Color(52, 59, 72));
        jLabelhome.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelhome.setForeground(new java.awt.Color(255, 255, 255));
        jLabelhome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hello_bangladesh/image/home_30px.png"))); // NOI18N
        jLabelhome.setText("Home");
        jLabelhome.setOpaque(true);
        jLabelhome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelhomeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelhomeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelhomeMouseExited(evt);
            }
        });
        jPanelmenu.add(jLabelhome, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 240, -1));

        jLabelemergencymenu.setBackground(new java.awt.Color(52, 59, 72));
        jLabelemergencymenu.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelemergencymenu.setForeground(new java.awt.Color(255, 255, 255));
        jLabelemergencymenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hello_bangladesh/image/emergency_30px.png"))); // NOI18N
        jLabelemergencymenu.setText("Emergency Service");
        jLabelemergencymenu.setOpaque(true);
        jLabelemergencymenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelemergencymenuMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelemergencymenuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelemergencymenuMouseExited(evt);
            }
        });
        jPanelmenu.add(jLabelemergencymenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 240, 30));

        jLabelreportmenu.setBackground(new java.awt.Color(52, 59, 72));
        jLabelreportmenu.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelreportmenu.setForeground(new java.awt.Color(255, 255, 255));
        jLabelreportmenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hello_bangladesh/image/report_30px.png"))); // NOI18N
        jLabelreportmenu.setText("Report");
        jLabelreportmenu.setOpaque(true);
        jLabelreportmenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelreportmenuMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelreportmenuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelreportmenuMouseExited(evt);
            }
        });
        jPanelmenu.add(jLabelreportmenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 240, -1));

        jLabelgovinfomenu.setBackground(new java.awt.Color(52, 59, 72));
        jLabelgovinfomenu.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelgovinfomenu.setForeground(new java.awt.Color(255, 255, 255));
        jLabelgovinfomenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hello_bangladesh/image/info_30px.png"))); // NOI18N
        jLabelgovinfomenu.setText("Gov. Info");
        jLabelgovinfomenu.setOpaque(true);
        jLabelgovinfomenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelgovinfomenuMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelgovinfomenuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelgovinfomenuMouseExited(evt);
            }
        });
        jPanelmenu.add(jLabelgovinfomenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 240, 30));

        jLabelfeedbackmenu.setBackground(new java.awt.Color(52, 59, 72));
        jLabelfeedbackmenu.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelfeedbackmenu.setForeground(new java.awt.Color(255, 255, 255));
        jLabelfeedbackmenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hello_bangladesh/image/Feedback_30px.png"))); // NOI18N
        jLabelfeedbackmenu.setText("Feedback");
        jLabelfeedbackmenu.setOpaque(true);
        jLabelfeedbackmenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelfeedbackmenuMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelfeedbackmenuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelfeedbackmenuMouseExited(evt);
            }
        });
        jPanelmenu.add(jLabelfeedbackmenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 240, 30));

        jLabelsettingsmenu.setBackground(new java.awt.Color(52, 59, 72));
        jLabelsettingsmenu.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelsettingsmenu.setForeground(new java.awt.Color(255, 255, 255));
        jLabelsettingsmenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hello_bangladesh/image/Settings_30px.png"))); // NOI18N
        jLabelsettingsmenu.setText("Settings");
        jLabelsettingsmenu.setOpaque(true);
        jLabelsettingsmenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelsettingsmenuMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelsettingsmenuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelsettingsmenuMouseExited(evt);
            }
        });
        jPanelmenu.add(jLabelsettingsmenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 290, 240, 30));

        jLabelsupportmenu.setBackground(new java.awt.Color(52, 59, 72));
        jLabelsupportmenu.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelsupportmenu.setForeground(new java.awt.Color(255, 255, 255));
        jLabelsupportmenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hello_bangladesh/image/Customer_Support_30px.png"))); // NOI18N
        jLabelsupportmenu.setText("Help & Support");
        jLabelsupportmenu.setOpaque(true);
        jLabelsupportmenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelsupportmenuMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelsupportmenuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelsupportmenuMouseExited(evt);
            }
        });
        jPanelmenu.add(jLabelsupportmenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 330, 240, -1));

        jLabellogoutmenu.setBackground(new java.awt.Color(52, 59, 72));
        jLabellogoutmenu.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabellogoutmenu.setForeground(new java.awt.Color(255, 255, 255));
        jLabellogoutmenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hello_bangladesh/image/logout_30px.png"))); // NOI18N
        jLabellogoutmenu.setText("Log Out");
        jLabellogoutmenu.setOpaque(true);
        jLabellogoutmenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabellogoutmenuMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabellogoutmenuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabellogoutmenuMouseExited(evt);
            }
        });
        jPanelmenu.add(jLabellogoutmenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 370, 240, 30));
        jPanelmenu.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 240, 10));

        jLabelback.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hello_bangladesh/image/Back_Arrow_30px.png"))); // NOI18N
        jLabelback.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelbackMouseClicked(evt);
            }
        });
        jPanelmenu.add(jLabelback, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 10, -1, -1));

        getContentPane().add(jPanelmenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 240, 600));

        jPanelemergency.setBackground(new java.awt.Color(53, 59, 72));
        jPanelemergency.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanelemergencyMouseDragged(evt);
            }
        });
        jPanelemergency.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelemergencyMouseClicked(evt);
            }
        });
        jPanelemergency.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelemeregency.setBackground(new java.awt.Color(52, 59, 72));
        jLabelemeregency.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabelemeregency.setForeground(new java.awt.Color(255, 255, 255));
        jLabelemeregency.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelemeregency.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hello_bangladesh/image/emergency.png"))); // NOI18N
        jLabelemeregency.setText("Call 999");
        jLabelemeregency.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabelemeregency.setFocusable(false);
        jLabelemeregency.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabelemeregency.setOpaque(true);
        jLabelemeregency.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jLabelemeregency.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelemeregencyMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelemeregencyMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelemeregencyMouseExited(evt);
            }
        });
        jPanelemergency.add(jLabelemeregency, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 50, 150, 150));

        jLabeluser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hello_bangladesh/image/user.png"))); // NOI18N
        jLabeluser.setFocusable(false);
        jLabeluser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabeluserMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabeluserMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabeluserMouseExited(evt);
            }
        });
        jPanelemergency.add(jLabeluser, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 10, -1, -1));

        jLabelClose.setFont(new java.awt.Font("Adobe Devanagari", 0, 18)); // NOI18N
        jLabelClose.setForeground(new java.awt.Color(255, 0, 0));
        jLabelClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hello_bangladesh/image/close.png"))); // NOI18N
        jLabelClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelCloseMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelCloseMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelCloseMouseExited(evt);
            }
        });
        jPanelemergency.add(jLabelClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 10, 20, 20));

        jLabeMin.setFont(new java.awt.Font("Adobe Devanagari", 1, 24)); // NOI18N
        jLabeMin.setForeground(new java.awt.Color(255, 255, 102));
        jLabeMin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hello_bangladesh/image/minimize.png"))); // NOI18N
        jLabeMin.setToolTipText("");
        jLabeMin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabeMinMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabeMinMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabeMinMouseExited(evt);
            }
        });
        jPanelemergency.add(jLabeMin, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 10, 20, -1));

        jLabelmenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hello_bangladesh/image/menu.png"))); // NOI18N
        jLabelmenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelmenuMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelmenuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelmenuMouseExited(evt);
            }
        });
        jPanelemergency.add(jLabelmenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 30));

        jLabelpolice.setBackground(new java.awt.Color(52, 59, 72));
        jLabelpolice.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabelpolice.setForeground(new java.awt.Color(255, 255, 255));
        jLabelpolice.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelpolice.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hello_bangladesh/image/Police_100px.png"))); // NOI18N
        jLabelpolice.setText("Police");
        jLabelpolice.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabelpolice.setFocusable(false);
        jLabelpolice.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabelpolice.setOpaque(true);
        jLabelpolice.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jLabelpolice.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelpoliceMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelpoliceMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelpoliceMouseExited(evt);
            }
        });
        jPanelemergency.add(jLabelpolice, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 50, 150, 150));

        jLabelfireservice.setBackground(new java.awt.Color(52, 59, 72));
        jLabelfireservice.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabelfireservice.setForeground(new java.awt.Color(255, 255, 255));
        jLabelfireservice.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelfireservice.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hello_bangladesh/image/Fire_Truck_100px.png"))); // NOI18N
        jLabelfireservice.setText("Fire Service");
        jLabelfireservice.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabelfireservice.setFocusable(false);
        jLabelfireservice.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabelfireservice.setOpaque(true);
        jLabelfireservice.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jLabelfireservice.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelfireserviceMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelfireserviceMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelfireserviceMouseExited(evt);
            }
        });
        jPanelemergency.add(jLabelfireservice, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 50, 150, 150));

        jLabelambulaance.setBackground(new java.awt.Color(52, 59, 72));
        jLabelambulaance.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabelambulaance.setForeground(new java.awt.Color(255, 255, 255));
        jLabelambulaance.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelambulaance.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hello_bangladesh/image/Ambulance_100px.png"))); // NOI18N
        jLabelambulaance.setText("Ambulance");
        jLabelambulaance.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabelambulaance.setFocusable(false);
        jLabelambulaance.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabelambulaance.setOpaque(true);
        jLabelambulaance.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jLabelambulaance.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelambulaanceMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelambulaanceMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelambulaanceMouseExited(evt);
            }
        });
        jPanelemergency.add(jLabelambulaance, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 210, 150, 150));

        jLabelneighbours.setBackground(new java.awt.Color(52, 59, 72));
        jLabelneighbours.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabelneighbours.setForeground(new java.awt.Color(255, 255, 255));
        jLabelneighbours.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelneighbours.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hello_bangladesh/image/User_Groups_100px.png"))); // NOI18N
        jLabelneighbours.setText("Neighbours");
        jLabelneighbours.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabelneighbours.setFocusable(false);
        jLabelneighbours.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabelneighbours.setOpaque(true);
        jLabelneighbours.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jLabelneighbours.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelneighboursMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelneighboursMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelneighboursMouseExited(evt);
            }
        });
        jPanelemergency.add(jLabelneighbours, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 370, 150, 150));

        jLabelelectricity.setBackground(new java.awt.Color(52, 59, 72));
        jLabelelectricity.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabelelectricity.setForeground(new java.awt.Color(255, 255, 255));
        jLabelelectricity.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelelectricity.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hello_bangladesh/image/Light_100px.png"))); // NOI18N
        jLabelelectricity.setText("Electricity");
        jLabelelectricity.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabelelectricity.setFocusable(false);
        jLabelelectricity.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabelelectricity.setOpaque(true);
        jLabelelectricity.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jLabelelectricity.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelelectricityMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelelectricityMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelelectricityMouseExited(evt);
            }
        });
        jPanelemergency.add(jLabelelectricity, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 210, 150, 150));

        jLabelelwasa.setBackground(new java.awt.Color(52, 59, 72));
        jLabelelwasa.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabelelwasa.setForeground(new java.awt.Color(255, 255, 255));
        jLabelelwasa.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelelwasa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hello_bangladesh/image/Water_100px.png"))); // NOI18N
        jLabelelwasa.setText("Wasa");
        jLabelelwasa.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabelelwasa.setFocusable(false);
        jLabelelwasa.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabelelwasa.setOpaque(true);
        jLabelelwasa.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jLabelelwasa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelelwasaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelelwasaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelelwasaMouseExited(evt);
            }
        });
        jPanelemergency.add(jLabelelwasa, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 210, 150, 150));

        getContentPane().add(jPanelemergency, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1050, 600));

        bangladesh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hello_bangladesh/bangladesh map.png"))); // NOI18N
        getContentPane().add(bangladesh, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabeluserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabeluserMouseClicked
        jPanelpersonal.setVisible(true);
    }//GEN-LAST:event_jLabeluserMouseClicked

    private void jLabeluserMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabeluserMouseEntered
        ii = new ImageIcon(getClass().getResource("image\\user1.png"));
        jLabeluser.setIcon(ii);
    }//GEN-LAST:event_jLabeluserMouseEntered

    private void jLabeluserMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabeluserMouseExited
        ii = new ImageIcon(getClass().getResource("image\\user.png"));
        jLabeluser.setIcon(ii);
    }//GEN-LAST:event_jLabeluserMouseExited

    private void jLabelCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelCloseMouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabelCloseMouseClicked

    private void jLabelCloseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelCloseMouseEntered
        ii = new ImageIcon(getClass().getResource("image\\close1.png"));
        jLabelClose.setIcon(ii);
    }//GEN-LAST:event_jLabelCloseMouseEntered

    private void jLabelCloseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelCloseMouseExited
        ii = new ImageIcon(getClass().getResource("image\\close.png"));
        jLabelClose.setIcon(ii);
    }//GEN-LAST:event_jLabelCloseMouseExited

    private void jLabeMinMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabeMinMouseClicked
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_jLabeMinMouseClicked

    private void jLabeMinMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabeMinMouseEntered
        ii = new ImageIcon(getClass().getResource("image\\minimize1.png"));
        jLabeMin.setIcon(ii);
    }//GEN-LAST:event_jLabeMinMouseEntered

    private void jLabeMinMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabeMinMouseExited
        ii = new ImageIcon(getClass().getResource("image\\minimize.png"));
        jLabeMin.setIcon(ii);
    }//GEN-LAST:event_jLabeMinMouseExited

    private void jLabelmenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelmenuMouseClicked

        jPanelmenu.setVisible(true);
        jLabelmenu.setVisible(false);
    }//GEN-LAST:event_jLabelmenuMouseClicked

    private void jLabelmenuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelmenuMouseEntered
        ii = new ImageIcon(getClass().getResource("image\\menu1.png"));
        jLabelmenu.setIcon(ii);
    }//GEN-LAST:event_jLabelmenuMouseEntered

    private void jLabelmenuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelmenuMouseExited
        ii = new ImageIcon(getClass().getResource("image\\menu.png"));
        jLabelmenu.setIcon(ii);
    }//GEN-LAST:event_jLabelmenuMouseExited

    private void jPanelemergencyMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelemergencyMouseDragged
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanelemergencyMouseDragged

    private void jPanelemergencyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelemergencyMouseClicked
        jPanelmenu.setVisible(false);
        jLabelmenu.setVisible(true);
        jPanelpersonal.setVisible(false);
    }//GEN-LAST:event_jPanelemergencyMouseClicked

    private void jLabelhomeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelhomeMouseEntered
        jLabelhome.setBackground(new Color(39,60,117));
    }//GEN-LAST:event_jLabelhomeMouseEntered

    private void jLabelhomeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelhomeMouseExited
        jLabelhome.setBackground(new Color(53,59,72));
    }//GEN-LAST:event_jLabelhomeMouseExited

    private void jLabelemergencymenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelemergencymenuMouseClicked

        emergency emergency = new emergency();
        emergency.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabelemergencymenuMouseClicked

    private void jLabelemergencymenuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelemergencymenuMouseEntered
        jLabelemergencymenu.setBackground(new Color(39,60,117));
    }//GEN-LAST:event_jLabelemergencymenuMouseEntered

    private void jLabelemergencymenuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelemergencymenuMouseExited
        jLabelemergencymenu.setBackground(new Color(53,59,72));
    }//GEN-LAST:event_jLabelemergencymenuMouseExited

    private void jLabelreportmenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelreportmenuMouseClicked

        report report = new report();
        report.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabelreportmenuMouseClicked

    private void jLabelreportmenuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelreportmenuMouseEntered
        jLabelreportmenu.setBackground(new Color(39,60,117));
    }//GEN-LAST:event_jLabelreportmenuMouseEntered

    private void jLabelreportmenuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelreportmenuMouseExited
        jLabelreportmenu.setBackground(new Color(53,59,72));
    }//GEN-LAST:event_jLabelreportmenuMouseExited

    private void jLabelgovinfomenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelgovinfomenuMouseClicked

        govinfo govinfo = new govinfo();
        govinfo.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabelgovinfomenuMouseClicked

    private void jLabelgovinfomenuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelgovinfomenuMouseEntered
        jLabelgovinfomenu.setBackground(new Color(39,60,117));
    }//GEN-LAST:event_jLabelgovinfomenuMouseEntered

    private void jLabelgovinfomenuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelgovinfomenuMouseExited
        jLabelgovinfomenu.setBackground(new Color(53,59,72));
    }//GEN-LAST:event_jLabelgovinfomenuMouseExited

    private void jLabelfeedbackmenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelfeedbackmenuMouseClicked

        feedback feedback = new feedback();
        feedback.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabelfeedbackmenuMouseClicked

    private void jLabelfeedbackmenuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelfeedbackmenuMouseEntered
        jLabelfeedbackmenu.setBackground(new Color(39,60,117));
    }//GEN-LAST:event_jLabelfeedbackmenuMouseEntered

    private void jLabelfeedbackmenuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelfeedbackmenuMouseExited
        jLabelfeedbackmenu.setBackground(new Color(53,59,72));
    }//GEN-LAST:event_jLabelfeedbackmenuMouseExited

    private void jLabelsettingsmenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelsettingsmenuMouseClicked

        settings settings = new settings();
        settings.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabelsettingsmenuMouseClicked

    private void jLabelsettingsmenuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelsettingsmenuMouseEntered
        jLabelsettingsmenu.setBackground(new Color(39,60,117));
    }//GEN-LAST:event_jLabelsettingsmenuMouseEntered

    private void jLabelsettingsmenuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelsettingsmenuMouseExited
        jLabelsettingsmenu.setBackground(new Color(53,59,72));
    }//GEN-LAST:event_jLabelsettingsmenuMouseExited

    private void jLabelsupportmenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelsupportmenuMouseClicked

        help help = new help();
        help.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabelsupportmenuMouseClicked

    private void jLabelsupportmenuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelsupportmenuMouseEntered
        jLabelsupportmenu.setBackground(new Color(39,60,117));
    }//GEN-LAST:event_jLabelsupportmenuMouseEntered

    private void jLabelsupportmenuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelsupportmenuMouseExited
        jLabelsupportmenu.setBackground(new Color(53,59,72));
    }//GEN-LAST:event_jLabelsupportmenuMouseExited

    private void jLabellogoutmenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabellogoutmenuMouseClicked

        login login = new login();
        login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabellogoutmenuMouseClicked

    private void jLabellogoutmenuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabellogoutmenuMouseEntered
        jLabellogoutmenu.setBackground(new Color(39,60,117));
    }//GEN-LAST:event_jLabellogoutmenuMouseEntered

    private void jLabellogoutmenuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabellogoutmenuMouseExited
        jLabellogoutmenu.setBackground(new Color(53,59,72));
    }//GEN-LAST:event_jLabellogoutmenuMouseExited

    private void jLabelbackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelbackMouseClicked
        jLabelmenu.setVisible(true);
        jPanelmenu.setVisible(false);
    }//GEN-LAST:event_jLabelbackMouseClicked

    private void jLabellogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabellogoutMouseClicked

        login login = new login();
        login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabellogoutMouseClicked

    private void jLabellogoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabellogoutMouseEntered
        jLabellogout.setBackground(new Color(39,60,117));
    }//GEN-LAST:event_jLabellogoutMouseEntered

    private void jLabellogoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabellogoutMouseExited
        jLabellogout.setBackground(new Color(53,59,72));
    }//GEN-LAST:event_jLabellogoutMouseExited

    private void jLabelsettingsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelsettingsMouseClicked

        settings settings = new settings();
        settings.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabelsettingsMouseClicked

    private void jLabelsettingsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelsettingsMouseEntered
        jLabelsettings.setBackground(new Color(39,60,117));
    }//GEN-LAST:event_jLabelsettingsMouseEntered

    private void jLabelsettingsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelsettingsMouseExited
        jLabelsettings.setBackground(new Color(53,59,72));
    }//GEN-LAST:event_jLabelsettingsMouseExited

    private void jLabelhelpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelhelpMouseClicked

        help help = new help();
        help.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabelhelpMouseClicked

    private void jLabelhelpMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelhelpMouseEntered
        jLabelhelp.setBackground(new Color(39,60,117));
    }//GEN-LAST:event_jLabelhelpMouseEntered

    private void jLabelhelpMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelhelpMouseExited
        jLabelhelp.setBackground(new Color(53,59,72));
    }//GEN-LAST:event_jLabelhelpMouseExited

    private void jLabelemeregencyMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelemeregencyMouseExited
        jLabelemeregency.setBackground(new Color(53,59,72));
    }//GEN-LAST:event_jLabelemeregencyMouseExited

    private void jLabelemeregencyMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelemeregencyMouseEntered
        jLabelemeregency.setBackground(new Color(39,60,117));
    }//GEN-LAST:event_jLabelemeregencyMouseEntered

    private void jLabelemeregencyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelemeregencyMouseClicked
        JOptionPane.showMessageDialog(null,"Call 999");
    }//GEN-LAST:event_jLabelemeregencyMouseClicked

    private void jLabelpoliceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelpoliceMouseClicked
        JOptionPane.showMessageDialog(null,"CAll 100 ");
    }//GEN-LAST:event_jLabelpoliceMouseClicked

    private void jLabelpoliceMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelpoliceMouseEntered
          jLabelpolice.setBackground(new Color(39,60,117));       
    }//GEN-LAST:event_jLabelpoliceMouseEntered

    private void jLabelpoliceMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelpoliceMouseExited
        jLabelpolice.setBackground(new Color(53,59,72));
    }//GEN-LAST:event_jLabelpoliceMouseExited

    private void jLabelfireserviceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelfireserviceMouseClicked
        JOptionPane.showMessageDialog(null,"Call (02)9555555");
    }//GEN-LAST:event_jLabelfireserviceMouseClicked

    private void jLabelfireserviceMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelfireserviceMouseEntered
        jLabelfireservice.setBackground(new Color(39,60,117));
    }//GEN-LAST:event_jLabelfireserviceMouseEntered

    private void jLabelfireserviceMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelfireserviceMouseExited
        jLabelfireservice.setBackground(new Color(53,59,72));
    }//GEN-LAST:event_jLabelfireserviceMouseExited

    private void jLabelambulaanceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelambulaanceMouseClicked
        JOptionPane.showMessageDialog(null,"Call 10610");
    }//GEN-LAST:event_jLabelambulaanceMouseClicked

    private void jLabelambulaanceMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelambulaanceMouseEntered
        jLabelambulaance.setBackground(new Color(39,60,117));
    }//GEN-LAST:event_jLabelambulaanceMouseEntered

    private void jLabelambulaanceMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelambulaanceMouseExited
        jLabelambulaance.setBackground(new Color(53,59,72));
    }//GEN-LAST:event_jLabelambulaanceMouseExited

    private void jLabelneighboursMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelneighboursMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabelneighboursMouseClicked

    private void jLabelneighboursMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelneighboursMouseEntered
        jLabelneighbours.setBackground(new Color(39,60,117));
    }//GEN-LAST:event_jLabelneighboursMouseEntered

    private void jLabelneighboursMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelneighboursMouseExited
        jLabelneighbours.setBackground(new Color(53,59,72));
    }//GEN-LAST:event_jLabelneighboursMouseExited

    private void jLabelelectricityMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelelectricityMouseClicked
         JOptionPane.showMessageDialog(null,"Call 01730320306");
    }//GEN-LAST:event_jLabelelectricityMouseClicked

    private void jLabelelectricityMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelelectricityMouseEntered
       jLabelelectricity.setBackground(new Color(39,60,117));
    }//GEN-LAST:event_jLabelelectricityMouseEntered

    private void jLabelelectricityMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelelectricityMouseExited
        jLabelelectricity.setBackground(new Color(53,59,72));
    }//GEN-LAST:event_jLabelelectricityMouseExited

    private void jLabelelwasaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelelwasaMouseClicked
        JOptionPane.showMessageDialog(null,"Call 01819229420");
    }//GEN-LAST:event_jLabelelwasaMouseClicked

    private void jLabelelwasaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelelwasaMouseEntered
        jLabelelwasa.setBackground(new Color(39,60,117));
    }//GEN-LAST:event_jLabelelwasaMouseEntered

    private void jLabelelwasaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelelwasaMouseExited
        jLabelelwasa.setBackground(new Color(53,59,72));
    }//GEN-LAST:event_jLabelelwasaMouseExited

    private void jLabelhomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelhomeMouseClicked
        home home = new home();
        home.setVisible(true);
        this.dispose();    
    }//GEN-LAST:event_jLabelhomeMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(emergency.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(emergency.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(emergency.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(emergency.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new emergency().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bangladesh;
    private javax.swing.JLabel jLabeMin;
    private javax.swing.JLabel jLabelClose;
    private javax.swing.JLabel jLabelambulaance;
    private javax.swing.JLabel jLabelback;
    private javax.swing.JLabel jLabelelectricity;
    private javax.swing.JLabel jLabelelwasa;
    private javax.swing.JLabel jLabelemeregency;
    private javax.swing.JLabel jLabelemergencymenu;
    private javax.swing.JLabel jLabelfeedbackmenu;
    private javax.swing.JLabel jLabelfireservice;
    private javax.swing.JLabel jLabelgovinfomenu;
    private javax.swing.JLabel jLabelhelp;
    private javax.swing.JLabel jLabelhome;
    private javax.swing.JLabel jLabellogout;
    private javax.swing.JLabel jLabellogoutmenu;
    private javax.swing.JLabel jLabelmenu;
    private javax.swing.JLabel jLabelneighbours;
    private javax.swing.JLabel jLabelpolice;
    private javax.swing.JLabel jLabelreportmenu;
    private javax.swing.JLabel jLabelsettings;
    private javax.swing.JLabel jLabelsettingsmenu;
    private javax.swing.JLabel jLabelsupportmenu;
    private javax.swing.JLabel jLabeluser;
    private javax.swing.JPanel jPanelemergency;
    private javax.swing.JPanel jPanelmenu;
    private javax.swing.JPanel jPanelpersonal;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
