/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hello_bangladesh;

import java.awt.Color;
import java.awt.Desktop;
import java.io.IOException;
import java.net.URI;
import java.net.URISyntaxException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFrame;

/**
 *
 * @author Asus
 */
public class govinfo extends javax.swing.JFrame {

    ImageIcon ii,icon;
    
    public govinfo() {
        initComponents();
        
        pack();
         icon = new ImageIcon(getClass().getResource("image\\bangladesh map_316px.png"));
         setIconImage(icon.getImage()); // set java frame icon
         setLocationRelativeTo(null);
        setBackground(new Color(0,0,0,0)); 
        jPanelgovinfo.setBackground(new Color(53,59,72,230));
        //bangladesh.setBackground(new Color(0,0,0,55));
        jPanelmenu.setVisible(false);
        //jPanelmenu.setBackground(new Color(53,59,72,100));
        jPanelpersonal.setVisible(false);
        jPanelpersonal.setBackground(new Color(53,59,72,100));
        //jLabeldshe.setOpaque(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelmenu = new javax.swing.JPanel();
        jLabelhome = new javax.swing.JLabel();
        jLabelemergencymenu = new javax.swing.JLabel();
        jLabelreportmenu = new javax.swing.JLabel();
        jLabelgovinfomenu = new javax.swing.JLabel();
        jLabelfeedbackmenu = new javax.swing.JLabel();
        jLabelsettingsmenu = new javax.swing.JLabel();
        jLabelsupportmenu = new javax.swing.JLabel();
        jLabellogoutmenu = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabelback = new javax.swing.JLabel();
        jPanelpersonal = new javax.swing.JPanel();
        jLabellogout = new javax.swing.JLabel();
        jLabelsettings = new javax.swing.JLabel();
        jLabelhelp = new javax.swing.JLabel();
        jPanelgovinfo = new javax.swing.JPanel();
        jLabeluser = new javax.swing.JLabel();
        jLabelClose = new javax.swing.JLabel();
        jLabeMin = new javax.swing.JLabel();
        jLabelmenu = new javax.swing.JLabel();
        jLabelgovinfo = new javax.swing.JLabel();
        jLabeldshe = new javax.swing.JLabel();
        jLabeldmp = new javax.swing.JLabel();
        jLabelrajuk = new javax.swing.JLabel();
        jLabelnbr = new javax.swing.JLabel();
        jLabelacc = new javax.swing.JLabel();
        bangladesh = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelmenu.setBackground(new java.awt.Color(53, 59, 73));
        jPanelmenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelhome.setBackground(new java.awt.Color(52, 59, 72));
        jLabelhome.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelhome.setForeground(new java.awt.Color(255, 255, 255));
        jLabelhome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hello_bangladesh/image/home_30px.png"))); // NOI18N
        jLabelhome.setText("Home");
        jLabelhome.setOpaque(true);
        jLabelhome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelhomeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelhomeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelhomeMouseExited(evt);
            }
        });
        jPanelmenu.add(jLabelhome, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 240, -1));

        jLabelemergencymenu.setBackground(new java.awt.Color(52, 59, 72));
        jLabelemergencymenu.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelemergencymenu.setForeground(new java.awt.Color(255, 255, 255));
        jLabelemergencymenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hello_bangladesh/image/emergency_30px.png"))); // NOI18N
        jLabelemergencymenu.setText("Emergency Service");
        jLabelemergencymenu.setOpaque(true);
        jLabelemergencymenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelemergencymenuMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelemergencymenuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelemergencymenuMouseExited(evt);
            }
        });
        jPanelmenu.add(jLabelemergencymenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 240, 30));

        jLabelreportmenu.setBackground(new java.awt.Color(52, 59, 72));
        jLabelreportmenu.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelreportmenu.setForeground(new java.awt.Color(255, 255, 255));
        jLabelreportmenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hello_bangladesh/image/report_30px.png"))); // NOI18N
        jLabelreportmenu.setText("Report");
        jLabelreportmenu.setOpaque(true);
        jLabelreportmenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelreportmenuMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelreportmenuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelreportmenuMouseExited(evt);
            }
        });
        jPanelmenu.add(jLabelreportmenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 240, -1));

        jLabelgovinfomenu.setBackground(new java.awt.Color(52, 59, 72));
        jLabelgovinfomenu.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelgovinfomenu.setForeground(new java.awt.Color(255, 255, 255));
        jLabelgovinfomenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hello_bangladesh/image/info_30px.png"))); // NOI18N
        jLabelgovinfomenu.setText("Gov. Info");
        jLabelgovinfomenu.setOpaque(true);
        jLabelgovinfomenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelgovinfomenuMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelgovinfomenuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelgovinfomenuMouseExited(evt);
            }
        });
        jPanelmenu.add(jLabelgovinfomenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 240, 30));

        jLabelfeedbackmenu.setBackground(new java.awt.Color(52, 59, 72));
        jLabelfeedbackmenu.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelfeedbackmenu.setForeground(new java.awt.Color(255, 255, 255));
        jLabelfeedbackmenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hello_bangladesh/image/Feedback_30px.png"))); // NOI18N
        jLabelfeedbackmenu.setText("Feedback");
        jLabelfeedbackmenu.setOpaque(true);
        jLabelfeedbackmenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelfeedbackmenuMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelfeedbackmenuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelfeedbackmenuMouseExited(evt);
            }
        });
        jPanelmenu.add(jLabelfeedbackmenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 240, 30));

        jLabelsettingsmenu.setBackground(new java.awt.Color(52, 59, 72));
        jLabelsettingsmenu.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelsettingsmenu.setForeground(new java.awt.Color(255, 255, 255));
        jLabelsettingsmenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hello_bangladesh/image/Settings_30px.png"))); // NOI18N
        jLabelsettingsmenu.setText("Settings");
        jLabelsettingsmenu.setOpaque(true);
        jLabelsettingsmenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelsettingsmenuMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelsettingsmenuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelsettingsmenuMouseExited(evt);
            }
        });
        jPanelmenu.add(jLabelsettingsmenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 290, 240, 30));

        jLabelsupportmenu.setBackground(new java.awt.Color(52, 59, 72));
        jLabelsupportmenu.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelsupportmenu.setForeground(new java.awt.Color(255, 255, 255));
        jLabelsupportmenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hello_bangladesh/image/Customer_Support_30px.png"))); // NOI18N
        jLabelsupportmenu.setText("Help & Support");
        jLabelsupportmenu.setOpaque(true);
        jLabelsupportmenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelsupportmenuMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelsupportmenuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelsupportmenuMouseExited(evt);
            }
        });
        jPanelmenu.add(jLabelsupportmenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 330, 240, -1));

        jLabellogoutmenu.setBackground(new java.awt.Color(52, 59, 72));
        jLabellogoutmenu.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabellogoutmenu.setForeground(new java.awt.Color(255, 255, 255));
        jLabellogoutmenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hello_bangladesh/image/logout_30px.png"))); // NOI18N
        jLabellogoutmenu.setText("Log Out");
        jLabellogoutmenu.setOpaque(true);
        jLabellogoutmenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabellogoutmenuMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabellogoutmenuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabellogoutmenuMouseExited(evt);
            }
        });
        jPanelmenu.add(jLabellogoutmenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 370, 240, 30));
        jPanelmenu.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 240, 10));

        jLabelback.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hello_bangladesh/image/Back_Arrow_30px.png"))); // NOI18N
        jLabelback.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelbackMouseClicked(evt);
            }
        });
        jPanelmenu.add(jLabelback, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 10, -1, -1));

        getContentPane().add(jPanelmenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 240, 600));

        jPanelpersonal.setBackground(new java.awt.Color(53, 59, 73));
        jPanelpersonal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabellogout.setBackground(new java.awt.Color(52, 59, 72));
        jLabellogout.setForeground(new java.awt.Color(255, 255, 255));
        jLabellogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hello_bangladesh/image/logout.png"))); // NOI18N
        jLabellogout.setText("Log Out");
        jLabellogout.setOpaque(true);
        jLabellogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabellogoutMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabellogoutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabellogoutMouseExited(evt);
            }
        });
        jPanelpersonal.add(jLabellogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 90, 20));

        jLabelsettings.setBackground(new java.awt.Color(52, 59, 72));
        jLabelsettings.setForeground(new java.awt.Color(255, 255, 255));
        jLabelsettings.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hello_bangladesh/image/settings.png"))); // NOI18N
        jLabelsettings.setText("Settings");
        jLabelsettings.setOpaque(true);
        jLabelsettings.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelsettingsMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelsettingsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelsettingsMouseExited(evt);
            }
        });
        jPanelpersonal.add(jLabelsettings, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 90, 20));

        jLabelhelp.setBackground(new java.awt.Color(52, 59, 72));
        jLabelhelp.setForeground(new java.awt.Color(255, 255, 255));
        jLabelhelp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hello_bangladesh/image/help.png"))); // NOI18N
        jLabelhelp.setText("Help");
        jLabelhelp.setOpaque(true);
        jLabelhelp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelhelpMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelhelpMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelhelpMouseExited(evt);
            }
        });
        jPanelpersonal.add(jLabelhelp, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 90, 20));

        getContentPane().add(jPanelpersonal, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 40, 90, 60));

        jPanelgovinfo.setBackground(new java.awt.Color(53, 59, 72));
        jPanelgovinfo.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanelgovinfoMouseDragged(evt);
            }
        });
        jPanelgovinfo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelgovinfoMouseClicked(evt);
            }
        });
        jPanelgovinfo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabeluser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hello_bangladesh/image/user.png"))); // NOI18N
        jLabeluser.setFocusable(false);
        jLabeluser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabeluserMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabeluserMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabeluserMouseExited(evt);
            }
        });
        jPanelgovinfo.add(jLabeluser, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 10, -1, -1));

        jLabelClose.setFont(new java.awt.Font("Adobe Devanagari", 0, 18)); // NOI18N
        jLabelClose.setForeground(new java.awt.Color(255, 0, 0));
        jLabelClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hello_bangladesh/image/close.png"))); // NOI18N
        jLabelClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelCloseMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelCloseMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelCloseMouseExited(evt);
            }
        });
        jPanelgovinfo.add(jLabelClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 10, 20, 20));

        jLabeMin.setFont(new java.awt.Font("Adobe Devanagari", 1, 24)); // NOI18N
        jLabeMin.setForeground(new java.awt.Color(255, 255, 102));
        jLabeMin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hello_bangladesh/image/minimize.png"))); // NOI18N
        jLabeMin.setToolTipText("");
        jLabeMin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabeMinMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabeMinMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabeMinMouseExited(evt);
            }
        });
        jPanelgovinfo.add(jLabeMin, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 10, 20, -1));

        jLabelmenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hello_bangladesh/image/menu.png"))); // NOI18N
        jLabelmenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelmenuMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelmenuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelmenuMouseExited(evt);
            }
        });
        jPanelgovinfo.add(jLabelmenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 30));

        jLabelgovinfo.setBackground(new java.awt.Color(52, 59, 72));
        jLabelgovinfo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelgovinfo.setForeground(new java.awt.Color(255, 255, 255));
        jLabelgovinfo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelgovinfo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hello_bangladesh/image/govinfo.png"))); // NOI18N
        jLabelgovinfo.setText("Bangladesh Government Info");
        jLabelgovinfo.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jLabelgovinfo.setOpaque(true);
        jLabelgovinfo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelgovinfoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelgovinfoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelgovinfoMouseExited(evt);
            }
        });
        jPanelgovinfo.add(jLabelgovinfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, 370, 100));

        jLabeldshe.setBackground(new java.awt.Color(52, 59, 72));
        jLabeldshe.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabeldshe.setForeground(new java.awt.Color(255, 255, 255));
        jLabeldshe.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabeldshe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hello_bangladesh/image/dshe.png"))); // NOI18N
        jLabeldshe.setText("Education Board (DSHE)");
        jLabeldshe.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jLabeldshe.setOpaque(true);
        jLabeldshe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabeldsheMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabeldsheMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabeldsheMouseExited(evt);
            }
        });
        jPanelgovinfo.add(jLabeldshe, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 300, 370, 90));

        jLabeldmp.setBackground(new java.awt.Color(52, 59, 72));
        jLabeldmp.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabeldmp.setForeground(new java.awt.Color(255, 255, 255));
        jLabeldmp.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabeldmp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hello_bangladesh/image/dhaka-metropolitan-police-logo-C8D559AE4B-seeklogo.com.png"))); // NOI18N
        jLabeldmp.setText("Dhaka Metropolitan Police");
        jLabeldmp.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jLabeldmp.setOpaque(true);
        jLabeldmp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabeldmpMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabeldmpMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabeldmpMouseExited(evt);
            }
        });
        jPanelgovinfo.add(jLabeldmp, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 90, 330, 90));

        jLabelrajuk.setBackground(new java.awt.Color(52, 59, 72));
        jLabelrajuk.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelrajuk.setForeground(new java.awt.Color(255, 255, 255));
        jLabelrajuk.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelrajuk.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hello_bangladesh/image/220px-Rajdhani_Unnayan_Kartripakkha_Logo.jpg"))); // NOI18N
        jLabelrajuk.setText("RAJUK");
        jLabelrajuk.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jLabelrajuk.setOpaque(true);
        jLabelrajuk.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelrajukMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelrajukMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelrajukMouseExited(evt);
            }
        });
        jPanelgovinfo.add(jLabelrajuk, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 290, 330, 110));

        jLabelnbr.setBackground(new java.awt.Color(52, 59, 72));
        jLabelnbr.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelnbr.setForeground(new java.awt.Color(255, 255, 255));
        jLabelnbr.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelnbr.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hello_bangladesh/image/NBR-logo.jpg"))); // NOI18N
        jLabelnbr.setText("National Board of Revenue(NBR)");
        jLabelnbr.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jLabelnbr.setOpaque(true);
        jLabelnbr.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelnbrMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelnbrMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelnbrMouseExited(evt);
            }
        });
        jPanelgovinfo.add(jLabelnbr, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 200, 370, 90));

        jLabelacc.setBackground(new java.awt.Color(52, 59, 72));
        jLabelacc.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelacc.setForeground(new java.awt.Color(255, 255, 255));
        jLabelacc.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelacc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hello_bangladesh/image/1054px-দুদকের_লোগো.svg.png"))); // NOI18N
        jLabelacc.setText("Anti-Corruption Commission");
        jLabelacc.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jLabelacc.setOpaque(true);
        jLabelacc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelaccMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelaccMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelaccMouseExited(evt);
            }
        });
        jPanelgovinfo.add(jLabelacc, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 190, 330, 90));

        getContentPane().add(jPanelgovinfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1050, 600));

        bangladesh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hello_bangladesh/bangladesh map.png"))); // NOI18N
        getContentPane().add(bangladesh, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelhomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelhomeMouseClicked
        home home = new home();
        home.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabelhomeMouseClicked

    private void jLabelhomeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelhomeMouseEntered
        jLabelhome.setBackground(new Color(39,60,117));
    }//GEN-LAST:event_jLabelhomeMouseEntered

    private void jLabelhomeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelhomeMouseExited
        jLabelhome.setBackground(new Color(53,59,72));
    }//GEN-LAST:event_jLabelhomeMouseExited

    private void jLabelemergencymenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelemergencymenuMouseClicked

        emergency emergency = new emergency();
        emergency.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabelemergencymenuMouseClicked

    private void jLabelemergencymenuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelemergencymenuMouseEntered
        jLabelemergencymenu.setBackground(new Color(39,60,117));
    }//GEN-LAST:event_jLabelemergencymenuMouseEntered

    private void jLabelemergencymenuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelemergencymenuMouseExited
        jLabelemergencymenu.setBackground(new Color(53,59,72));
    }//GEN-LAST:event_jLabelemergencymenuMouseExited

    private void jLabelreportmenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelreportmenuMouseClicked

        report report = new report();
        report.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabelreportmenuMouseClicked

    private void jLabelreportmenuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelreportmenuMouseEntered
        jLabelreportmenu.setBackground(new Color(39,60,117));
    }//GEN-LAST:event_jLabelreportmenuMouseEntered

    private void jLabelreportmenuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelreportmenuMouseExited
        jLabelreportmenu.setBackground(new Color(53,59,72));
    }//GEN-LAST:event_jLabelreportmenuMouseExited

    private void jLabelgovinfomenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelgovinfomenuMouseClicked

        govinfo govinfo = new govinfo();
        govinfo.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabelgovinfomenuMouseClicked

    private void jLabelgovinfomenuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelgovinfomenuMouseEntered
        jLabelgovinfomenu.setBackground(new Color(39,60,117));
    }//GEN-LAST:event_jLabelgovinfomenuMouseEntered

    private void jLabelgovinfomenuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelgovinfomenuMouseExited
        jLabelgovinfomenu.setBackground(new Color(53,59,72));
    }//GEN-LAST:event_jLabelgovinfomenuMouseExited

    private void jLabelfeedbackmenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelfeedbackmenuMouseClicked

        feedback feedback = new feedback();
        feedback.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabelfeedbackmenuMouseClicked

    private void jLabelfeedbackmenuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelfeedbackmenuMouseEntered
        jLabelfeedbackmenu.setBackground(new Color(39,60,117));
    }//GEN-LAST:event_jLabelfeedbackmenuMouseEntered

    private void jLabelfeedbackmenuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelfeedbackmenuMouseExited
        jLabelfeedbackmenu.setBackground(new Color(53,59,72));
    }//GEN-LAST:event_jLabelfeedbackmenuMouseExited

    private void jLabelsettingsmenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelsettingsmenuMouseClicked

        settings settings = new settings();
        settings.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabelsettingsmenuMouseClicked

    private void jLabelsettingsmenuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelsettingsmenuMouseEntered
        jLabelsettingsmenu.setBackground(new Color(39,60,117));
    }//GEN-LAST:event_jLabelsettingsmenuMouseEntered

    private void jLabelsettingsmenuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelsettingsmenuMouseExited
        jLabelsettingsmenu.setBackground(new Color(53,59,72));
    }//GEN-LAST:event_jLabelsettingsmenuMouseExited

    private void jLabelsupportmenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelsupportmenuMouseClicked

        help help = new help();
        help.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabelsupportmenuMouseClicked

    private void jLabelsupportmenuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelsupportmenuMouseEntered
        jLabelsupportmenu.setBackground(new Color(39,60,117));
    }//GEN-LAST:event_jLabelsupportmenuMouseEntered

    private void jLabelsupportmenuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelsupportmenuMouseExited
        jLabelsupportmenu.setBackground(new Color(53,59,72));
    }//GEN-LAST:event_jLabelsupportmenuMouseExited

    private void jLabellogoutmenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabellogoutmenuMouseClicked

        login login = new login();
        login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabellogoutmenuMouseClicked

    private void jLabellogoutmenuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabellogoutmenuMouseEntered
        jLabellogoutmenu.setBackground(new Color(39,60,117));
    }//GEN-LAST:event_jLabellogoutmenuMouseEntered

    private void jLabellogoutmenuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabellogoutmenuMouseExited
        jLabellogoutmenu.setBackground(new Color(53,59,72));
    }//GEN-LAST:event_jLabellogoutmenuMouseExited

    private void jLabelbackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelbackMouseClicked
        jLabelmenu.setVisible(true);
        jPanelmenu.setVisible(false);
    }//GEN-LAST:event_jLabelbackMouseClicked

    private void jLabellogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabellogoutMouseClicked

        login login = new login();
        login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabellogoutMouseClicked

    private void jLabellogoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabellogoutMouseEntered
        jLabellogout.setBackground(new Color(39,60,117));
    }//GEN-LAST:event_jLabellogoutMouseEntered

    private void jLabellogoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabellogoutMouseExited
        jLabellogout.setBackground(new Color(53,59,72));
    }//GEN-LAST:event_jLabellogoutMouseExited

    private void jLabelsettingsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelsettingsMouseClicked

        settings settings = new settings();
        settings.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabelsettingsMouseClicked

    private void jLabelsettingsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelsettingsMouseEntered
        jLabelsettings.setBackground(new Color(39,60,117));
    }//GEN-LAST:event_jLabelsettingsMouseEntered

    private void jLabelsettingsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelsettingsMouseExited
        jLabelsettings.setBackground(new Color(53,59,72));
    }//GEN-LAST:event_jLabelsettingsMouseExited

    private void jLabelhelpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelhelpMouseClicked

        help help = new help();
        help.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabelhelpMouseClicked

    private void jLabelhelpMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelhelpMouseEntered
        jLabelhelp.setBackground(new Color(39,60,117));
    }//GEN-LAST:event_jLabelhelpMouseEntered

    private void jLabelhelpMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelhelpMouseExited
        jLabelhelp.setBackground(new Color(53,59,72));
    }//GEN-LAST:event_jLabelhelpMouseExited

    private void jLabeluserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabeluserMouseClicked
        jPanelpersonal.setVisible(true);
    }//GEN-LAST:event_jLabeluserMouseClicked

    private void jLabeluserMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabeluserMouseEntered
        ii = new ImageIcon(getClass().getResource("image\\user1.png"));
        jLabeluser.setIcon(ii);
    }//GEN-LAST:event_jLabeluserMouseEntered

    private void jLabeluserMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabeluserMouseExited
        ii = new ImageIcon(getClass().getResource("image\\user.png"));
        jLabeluser.setIcon(ii);
    }//GEN-LAST:event_jLabeluserMouseExited

    private void jLabelCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelCloseMouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabelCloseMouseClicked

    private void jLabelCloseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelCloseMouseEntered
        ii = new ImageIcon(getClass().getResource("image\\close1.png"));
        jLabelClose.setIcon(ii);
    }//GEN-LAST:event_jLabelCloseMouseEntered

    private void jLabelCloseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelCloseMouseExited
        ii = new ImageIcon(getClass().getResource("image\\close.png"));
        jLabelClose.setIcon(ii);
    }//GEN-LAST:event_jLabelCloseMouseExited

    private void jLabeMinMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabeMinMouseClicked
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_jLabeMinMouseClicked

    private void jLabeMinMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabeMinMouseEntered
        ii = new ImageIcon(getClass().getResource("image\\minimize1.png"));
        jLabeMin.setIcon(ii);
    }//GEN-LAST:event_jLabeMinMouseEntered

    private void jLabeMinMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabeMinMouseExited
        ii = new ImageIcon(getClass().getResource("image\\minimize.png"));
        jLabeMin.setIcon(ii);
    }//GEN-LAST:event_jLabeMinMouseExited

    private void jLabelmenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelmenuMouseClicked

        jPanelmenu.setVisible(true);
        jLabelmenu.setVisible(false);
    }//GEN-LAST:event_jLabelmenuMouseClicked

    private void jLabelmenuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelmenuMouseEntered
        ii = new ImageIcon(getClass().getResource("image\\menu1.png"));
        jLabelmenu.setIcon(ii);
    }//GEN-LAST:event_jLabelmenuMouseEntered

    private void jLabelmenuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelmenuMouseExited
        ii = new ImageIcon(getClass().getResource("image\\menu.png"));
        jLabelmenu.setIcon(ii);
    }//GEN-LAST:event_jLabelmenuMouseExited

    private void jPanelgovinfoMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelgovinfoMouseDragged
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanelgovinfoMouseDragged

    private void jPanelgovinfoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelgovinfoMouseClicked
        jPanelmenu.setVisible(false);
        jLabelmenu.setVisible(true);
        jPanelpersonal.setVisible(false);
    }//GEN-LAST:event_jPanelgovinfoMouseClicked

    private void jLabelgovinfoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelgovinfoMouseClicked
       Desktop browser =  Desktop.getDesktop();
        try {
            browser.browse(new URI("http://www.bangladesh.gov.bd/index.php?lang=en"));
        } catch (IOException | URISyntaxException ex) {
            Logger.getLogger(govinfo.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jLabelgovinfoMouseClicked

    private void jLabelgovinfoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelgovinfoMouseEntered
        jLabelgovinfo.setBackground(new Color(39,60,117));
    }//GEN-LAST:event_jLabelgovinfoMouseEntered

    private void jLabelgovinfoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelgovinfoMouseExited
         jLabelgovinfo.setBackground(new Color(53,59,72));
    }//GEN-LAST:event_jLabelgovinfoMouseExited

    private void jLabeldsheMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabeldsheMouseClicked
         Desktop browser =  Desktop.getDesktop();
        try {
            browser.browse(new URI("http://www.dshe.gov.bd/"));
        } catch (IOException | URISyntaxException ex) {
            Logger.getLogger(govinfo.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jLabeldsheMouseClicked

    private void jLabeldsheMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabeldsheMouseEntered
       //jLabeldshe.setOpaque(true);
        jLabeldshe.setBackground(new Color(39,60,117));
    }//GEN-LAST:event_jLabeldsheMouseEntered

    private void jLabeldsheMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabeldsheMouseExited
      jLabeldshe.setBackground(new Color(53,59,72));
    }//GEN-LAST:event_jLabeldsheMouseExited

    private void jLabeldmpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabeldmpMouseClicked
         Desktop browser =  Desktop.getDesktop();
        try {
            browser.browse(new URI("https://dmp.gov.bd/"));
        } catch (IOException | URISyntaxException ex) {
            Logger.getLogger(govinfo.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jLabeldmpMouseClicked

    private void jLabeldmpMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabeldmpMouseEntered
        jLabeldmp.setBackground(new Color(39,60,117));
    }//GEN-LAST:event_jLabeldmpMouseEntered

    private void jLabeldmpMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabeldmpMouseExited
        jLabeldmp.setBackground(new Color(53,59,72));
    }//GEN-LAST:event_jLabeldmpMouseExited

    private void jLabelrajukMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelrajukMouseClicked
        Desktop browser =  Desktop.getDesktop();
        try {
            browser.browse(new URI("http://www.rajukdhaka.gov.bd/rajuk/webHome"));
        } catch (IOException | URISyntaxException ex) {
            Logger.getLogger(govinfo.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jLabelrajukMouseClicked

    private void jLabelrajukMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelrajukMouseEntered
        jLabelrajuk.setBackground(new Color(39,60,117));
    }//GEN-LAST:event_jLabelrajukMouseEntered

    private void jLabelrajukMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelrajukMouseExited
         jLabelrajuk.setBackground(new Color(53,59,72));
    }//GEN-LAST:event_jLabelrajukMouseExited

    private void jLabelnbrMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelnbrMouseClicked
         Desktop browser =  Desktop.getDesktop();
        try {
            browser.browse(new URI("http://nbr.gov.bd/"));
        } catch (IOException | URISyntaxException ex) {
            Logger.getLogger(govinfo.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jLabelnbrMouseClicked

    private void jLabelnbrMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelnbrMouseEntered
       jLabelnbr.setBackground(new Color(39,60,117));
    }//GEN-LAST:event_jLabelnbrMouseEntered

    private void jLabelnbrMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelnbrMouseExited
        jLabelnbr.setBackground(new Color(53,59,72));
    }//GEN-LAST:event_jLabelnbrMouseExited

    private void jLabelaccMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelaccMouseClicked
         Desktop browser =  Desktop.getDesktop();
        try {
            browser.browse(new URI("http://acc.org.bd/"));
        } catch (IOException | URISyntaxException ex) {
            Logger.getLogger(govinfo.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jLabelaccMouseClicked

    private void jLabelaccMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelaccMouseEntered
       jLabelacc.setBackground(new Color(39,60,117));
    }//GEN-LAST:event_jLabelaccMouseEntered

    private void jLabelaccMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelaccMouseExited
        jLabelacc.setBackground(new Color(53,59,72));
    }//GEN-LAST:event_jLabelaccMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(govinfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(govinfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(govinfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(govinfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new govinfo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bangladesh;
    private javax.swing.JLabel jLabeMin;
    private javax.swing.JLabel jLabelClose;
    private javax.swing.JLabel jLabelacc;
    private javax.swing.JLabel jLabelback;
    private javax.swing.JLabel jLabeldmp;
    private javax.swing.JLabel jLabeldshe;
    private javax.swing.JLabel jLabelemergencymenu;
    private javax.swing.JLabel jLabelfeedbackmenu;
    private javax.swing.JLabel jLabelgovinfo;
    private javax.swing.JLabel jLabelgovinfomenu;
    private javax.swing.JLabel jLabelhelp;
    private javax.swing.JLabel jLabelhome;
    private javax.swing.JLabel jLabellogout;
    private javax.swing.JLabel jLabellogoutmenu;
    private javax.swing.JLabel jLabelmenu;
    private javax.swing.JLabel jLabelnbr;
    private javax.swing.JLabel jLabelrajuk;
    private javax.swing.JLabel jLabelreportmenu;
    private javax.swing.JLabel jLabelsettings;
    private javax.swing.JLabel jLabelsettingsmenu;
    private javax.swing.JLabel jLabelsupportmenu;
    private javax.swing.JLabel jLabeluser;
    private javax.swing.JPanel jPanelgovinfo;
    private javax.swing.JPanel jPanelmenu;
    private javax.swing.JPanel jPanelpersonal;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
