/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hello_bangladesh;

import java.awt.Color;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Asus
 */
public class report extends javax.swing.JFrame {

    ImageIcon ii, icon;
    String TYPE, KIND;

    public report() {
        initComponents();

        pack();
        icon = new ImageIcon(getClass().getResource("image\\bangladesh map_316px.png"));
        setIconImage(icon.getImage()); // set java frame icon
        setLocationRelativeTo(null);
        setBackground(new Color(0, 0, 0, 0));
        jPanelreport.setBackground(new Color(53, 59, 72, 230));
        //bangladesh.setBackground(new Color(0,0,0,55));
        jPanelmenu.setVisible(false);
       // jPanelmenu.setBackground(new Color(53, 59, 72, 100));
        jPanelpersonal.setVisible(false);
        jPanelpersonal.setBackground(new Color(53, 59, 72, 100));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelmenu = new javax.swing.JPanel();
        jLabelhome = new javax.swing.JLabel();
        jLabelemergencymenu = new javax.swing.JLabel();
        jLabelreportmenu = new javax.swing.JLabel();
        jLabelgovinfomenu = new javax.swing.JLabel();
        jLabelfeedbackmenu = new javax.swing.JLabel();
        jLabelsettingsmenu = new javax.swing.JLabel();
        jLabelsupportmenu = new javax.swing.JLabel();
        jLabellogoutmenu = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabelback = new javax.swing.JLabel();
        jPanelpersonal = new javax.swing.JPanel();
        jLabellogout = new javax.swing.JLabel();
        jLabelsettings = new javax.swing.JLabel();
        jLabelhelp = new javax.swing.JLabel();
        jPanelreport = new javax.swing.JPanel();
        jLabeluser = new javax.swing.JLabel();
        jLabelClose = new javax.swing.JLabel();
        jLabeMin = new javax.swing.JLabel();
        jLabelmenu = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        giveadvice = new javax.swing.JRadioButton();
        reportproblem = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel10 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        bangladesh = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelmenu.setBackground(new java.awt.Color(53, 59, 73));
        jPanelmenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelhome.setBackground(new java.awt.Color(52, 59, 72));
        jLabelhome.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelhome.setForeground(new java.awt.Color(255, 255, 255));
        jLabelhome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hello_bangladesh/image/home_30px.png"))); // NOI18N
        jLabelhome.setText("Home");
        jLabelhome.setOpaque(true);
        jLabelhome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelhomeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelhomeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelhomeMouseExited(evt);
            }
        });
        jPanelmenu.add(jLabelhome, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 240, -1));

        jLabelemergencymenu.setBackground(new java.awt.Color(52, 59, 72));
        jLabelemergencymenu.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelemergencymenu.setForeground(new java.awt.Color(255, 255, 255));
        jLabelemergencymenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hello_bangladesh/image/emergency_30px.png"))); // NOI18N
        jLabelemergencymenu.setText("Emergency Service");
        jLabelemergencymenu.setOpaque(true);
        jLabelemergencymenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelemergencymenuMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelemergencymenuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelemergencymenuMouseExited(evt);
            }
        });
        jPanelmenu.add(jLabelemergencymenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 240, 30));

        jLabelreportmenu.setBackground(new java.awt.Color(52, 59, 72));
        jLabelreportmenu.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelreportmenu.setForeground(new java.awt.Color(255, 255, 255));
        jLabelreportmenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hello_bangladesh/image/report_30px.png"))); // NOI18N
        jLabelreportmenu.setText("Report");
        jLabelreportmenu.setOpaque(true);
        jLabelreportmenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelreportmenuMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelreportmenuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelreportmenuMouseExited(evt);
            }
        });
        jPanelmenu.add(jLabelreportmenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 240, -1));

        jLabelgovinfomenu.setBackground(new java.awt.Color(52, 59, 72));
        jLabelgovinfomenu.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelgovinfomenu.setForeground(new java.awt.Color(255, 255, 255));
        jLabelgovinfomenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hello_bangladesh/image/info_30px.png"))); // NOI18N
        jLabelgovinfomenu.setText("Gov. Info");
        jLabelgovinfomenu.setOpaque(true);
        jLabelgovinfomenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelgovinfomenuMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelgovinfomenuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelgovinfomenuMouseExited(evt);
            }
        });
        jPanelmenu.add(jLabelgovinfomenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 240, 30));

        jLabelfeedbackmenu.setBackground(new java.awt.Color(52, 59, 72));
        jLabelfeedbackmenu.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelfeedbackmenu.setForeground(new java.awt.Color(255, 255, 255));
        jLabelfeedbackmenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hello_bangladesh/image/Feedback_30px.png"))); // NOI18N
        jLabelfeedbackmenu.setText("Feedback");
        jLabelfeedbackmenu.setOpaque(true);
        jLabelfeedbackmenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelfeedbackmenuMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelfeedbackmenuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelfeedbackmenuMouseExited(evt);
            }
        });
        jPanelmenu.add(jLabelfeedbackmenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 240, 30));

        jLabelsettingsmenu.setBackground(new java.awt.Color(52, 59, 72));
        jLabelsettingsmenu.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelsettingsmenu.setForeground(new java.awt.Color(255, 255, 255));
        jLabelsettingsmenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hello_bangladesh/image/Settings_30px.png"))); // NOI18N
        jLabelsettingsmenu.setText("Settings");
        jLabelsettingsmenu.setOpaque(true);
        jLabelsettingsmenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelsettingsmenuMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelsettingsmenuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelsettingsmenuMouseExited(evt);
            }
        });
        jPanelmenu.add(jLabelsettingsmenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 290, 240, 30));

        jLabelsupportmenu.setBackground(new java.awt.Color(52, 59, 72));
        jLabelsupportmenu.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelsupportmenu.setForeground(new java.awt.Color(255, 255, 255));
        jLabelsupportmenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hello_bangladesh/image/Customer_Support_30px.png"))); // NOI18N
        jLabelsupportmenu.setText("Help & Support");
        jLabelsupportmenu.setOpaque(true);
        jLabelsupportmenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelsupportmenuMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelsupportmenuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelsupportmenuMouseExited(evt);
            }
        });
        jPanelmenu.add(jLabelsupportmenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 330, 240, -1));

        jLabellogoutmenu.setBackground(new java.awt.Color(52, 59, 72));
        jLabellogoutmenu.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabellogoutmenu.setForeground(new java.awt.Color(255, 255, 255));
        jLabellogoutmenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hello_bangladesh/image/logout_30px.png"))); // NOI18N
        jLabellogoutmenu.setText("Log Out");
        jLabellogoutmenu.setOpaque(true);
        jLabellogoutmenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabellogoutmenuMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabellogoutmenuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabellogoutmenuMouseExited(evt);
            }
        });
        jPanelmenu.add(jLabellogoutmenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 370, 240, 30));
        jPanelmenu.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 240, 10));

        jLabelback.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hello_bangladesh/image/Back_Arrow_30px.png"))); // NOI18N
        jLabelback.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelbackMouseClicked(evt);
            }
        });
        jPanelmenu.add(jLabelback, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 10, -1, -1));

        getContentPane().add(jPanelmenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 240, 600));

        jPanelpersonal.setBackground(new java.awt.Color(53, 59, 73));
        jPanelpersonal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabellogout.setBackground(new java.awt.Color(52, 59, 72));
        jLabellogout.setForeground(new java.awt.Color(255, 255, 255));
        jLabellogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hello_bangladesh/image/logout.png"))); // NOI18N
        jLabellogout.setText("Log Out");
        jLabellogout.setOpaque(true);
        jLabellogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabellogoutMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabellogoutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabellogoutMouseExited(evt);
            }
        });
        jPanelpersonal.add(jLabellogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 90, 20));

        jLabelsettings.setBackground(new java.awt.Color(52, 59, 72));
        jLabelsettings.setForeground(new java.awt.Color(255, 255, 255));
        jLabelsettings.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hello_bangladesh/image/settings.png"))); // NOI18N
        jLabelsettings.setText("Settings");
        jLabelsettings.setOpaque(true);
        jLabelsettings.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelsettingsMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelsettingsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelsettingsMouseExited(evt);
            }
        });
        jPanelpersonal.add(jLabelsettings, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 90, 20));

        jLabelhelp.setBackground(new java.awt.Color(52, 59, 72));
        jLabelhelp.setForeground(new java.awt.Color(255, 255, 255));
        jLabelhelp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hello_bangladesh/image/help.png"))); // NOI18N
        jLabelhelp.setText("Help");
        jLabelhelp.setOpaque(true);
        jLabelhelp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelhelpMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelhelpMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelhelpMouseExited(evt);
            }
        });
        jPanelpersonal.add(jLabelhelp, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 90, 20));

        getContentPane().add(jPanelpersonal, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 40, 90, 60));

        jPanelreport.setBackground(new java.awt.Color(53, 59, 72));
        jPanelreport.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanelreportMouseDragged(evt);
            }
        });
        jPanelreport.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelreportMouseClicked(evt);
            }
        });
        jPanelreport.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabeluser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hello_bangladesh/image/user.png"))); // NOI18N
        jLabeluser.setFocusable(false);
        jLabeluser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabeluserMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabeluserMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabeluserMouseExited(evt);
            }
        });
        jPanelreport.add(jLabeluser, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 10, -1, -1));

        jLabelClose.setFont(new java.awt.Font("Adobe Devanagari", 0, 18)); // NOI18N
        jLabelClose.setForeground(new java.awt.Color(255, 0, 0));
        jLabelClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hello_bangladesh/image/close.png"))); // NOI18N
        jLabelClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelCloseMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelCloseMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelCloseMouseExited(evt);
            }
        });
        jPanelreport.add(jLabelClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 10, 20, 20));

        jLabeMin.setFont(new java.awt.Font("Adobe Devanagari", 1, 24)); // NOI18N
        jLabeMin.setForeground(new java.awt.Color(255, 255, 102));
        jLabeMin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hello_bangladesh/image/minimize.png"))); // NOI18N
        jLabeMin.setToolTipText("");
        jLabeMin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabeMinMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabeMinMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabeMinMouseExited(evt);
            }
        });
        jPanelreport.add(jLabeMin, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 10, 20, -1));

        jLabelmenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hello_bangladesh/image/menu.png"))); // NOI18N
        jLabelmenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelmenuMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelmenuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelmenuMouseExited(evt);
            }
        });
        jPanelreport.add(jLabelmenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 30));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Type of Objection:");
        jPanelreport.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 150, 150, 20));

        giveadvice.setBackground(new java.awt.Color(53, 59, 72));
        giveadvice.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        giveadvice.setForeground(new java.awt.Color(255, 255, 255));
        giveadvice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                giveadviceActionPerformed(evt);
            }
        });
        jPanelreport.add(giveadvice, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 150, 20, 20));

        reportproblem.setBackground(new java.awt.Color(53, 59, 72));
        reportproblem.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        reportproblem.setForeground(new java.awt.Color(255, 255, 255));
        reportproblem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reportproblemActionPerformed(evt);
            }
        });
        jPanelreport.add(reportproblem, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 150, 20, 20));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("I'd like to give advice");
        jPanelreport.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 150, 190, 20));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText(" I'd like to report a problem");
        jPanelreport.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 150, 230, 20));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("and bring you a superb citizen experience. ");
        jPanelreport.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 70, 470, 40));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("What kind of objection is this?");
        jPanelreport.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 200, -1, -1));

        jComboBox1.setBackground(new java.awt.Color(53, 59, 72));
        jComboBox1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jComboBox1.setForeground(new java.awt.Color(255, 255, 255));
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "~Select One~", "Corruption", "Mismanagement", "Fake News", "Others" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jPanelreport.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 200, 470, 30));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("We highly appreciate your objection and will try our best to improve our serviece ");
        jPanelreport.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 30, 830, 40));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Related link:\t");
        jPanelreport.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 400, 100, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Description:");
        jPanelreport.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 310, 100, 30));

        jTextArea2.setBackground(new java.awt.Color(53, 59, 72));
        jTextArea2.setColumns(20);
        jTextArea2.setForeground(new java.awt.Color(255, 255, 255));
        jTextArea2.setRows(5);
        jScrollPane2.setViewportView(jTextArea2);

        jPanelreport.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 290, 300, 80));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Suggestion:");
        jPanelreport.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 310, 100, 30));

        jTextArea1.setBackground(new java.awt.Color(53, 59, 72));
        jTextArea1.setColumns(20);
        jTextArea1.setForeground(new java.awt.Color(255, 255, 255));
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jPanelreport.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 290, 300, 80));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Upload Evidence:");
        jPanelreport.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 400, 150, 30));

        jTextField1.setBackground(new java.awt.Color(53, 59, 72));
        jTextField1.setForeground(new java.awt.Color(255, 255, 255));
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jPanelreport.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 400, 270, 30));

        jButton4.setBackground(new java.awt.Color(53, 59, 72));
        jButton4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Upload");
        jButton4.setBorder(null);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanelreport.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 400, 120, 30));

        jButton5.setBackground(new java.awt.Color(53, 59, 72));
        jButton5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("Submit");
        jButton5.setBorder(null);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanelreport.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 500, 120, 30));

        getContentPane().add(jPanelreport, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1050, 600));

        bangladesh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hello_bangladesh/bangladesh map.png"))); // NOI18N
        getContentPane().add(bangladesh, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabeluserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabeluserMouseClicked
        jPanelpersonal.setVisible(true);
    }//GEN-LAST:event_jLabeluserMouseClicked

    private void jLabeluserMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabeluserMouseEntered
        ii = new ImageIcon(getClass().getResource("image\\user1.png"));
        jLabeluser.setIcon(ii);
    }//GEN-LAST:event_jLabeluserMouseEntered

    private void jLabeluserMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabeluserMouseExited
        ii = new ImageIcon(getClass().getResource("image\\user.png"));
        jLabeluser.setIcon(ii);
    }//GEN-LAST:event_jLabeluserMouseExited

    private void jLabelCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelCloseMouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabelCloseMouseClicked

    private void jLabelCloseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelCloseMouseEntered
        ii = new ImageIcon(getClass().getResource("image\\close1.png"));
        jLabelClose.setIcon(ii);
    }//GEN-LAST:event_jLabelCloseMouseEntered

    private void jLabelCloseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelCloseMouseExited
        ii = new ImageIcon(getClass().getResource("image\\close.png"));
        jLabelClose.setIcon(ii);
    }//GEN-LAST:event_jLabelCloseMouseExited

    private void jLabeMinMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabeMinMouseClicked
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_jLabeMinMouseClicked

    private void jLabeMinMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabeMinMouseEntered
        ii = new ImageIcon(getClass().getResource("image\\minimize1.png"));
        jLabeMin.setIcon(ii);
    }//GEN-LAST:event_jLabeMinMouseEntered

    private void jLabeMinMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabeMinMouseExited
        ii = new ImageIcon(getClass().getResource("image\\minimize.png"));
        jLabeMin.setIcon(ii);
    }//GEN-LAST:event_jLabeMinMouseExited

    private void jLabelmenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelmenuMouseClicked

        jPanelmenu.setVisible(true);
        jLabelmenu.setVisible(false);
    }//GEN-LAST:event_jLabelmenuMouseClicked

    private void jLabelmenuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelmenuMouseEntered
        ii = new ImageIcon(getClass().getResource("image\\menu1.png"));
        jLabelmenu.setIcon(ii);
    }//GEN-LAST:event_jLabelmenuMouseEntered

    private void jLabelmenuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelmenuMouseExited
        ii = new ImageIcon(getClass().getResource("image\\menu.png"));
        jLabelmenu.setIcon(ii);
    }//GEN-LAST:event_jLabelmenuMouseExited

    private void jPanelreportMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelreportMouseDragged
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanelreportMouseDragged

    private void jPanelreportMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelreportMouseClicked
        jPanelmenu.setVisible(false);
        jLabelmenu.setVisible(true);
        jPanelpersonal.setVisible(false);
    }//GEN-LAST:event_jPanelreportMouseClicked

    private void jLabellogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabellogoutMouseClicked

        login login = new login();
        login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabellogoutMouseClicked

    private void jLabellogoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabellogoutMouseEntered
        jLabellogout.setBackground(new Color(39, 60, 117));
    }//GEN-LAST:event_jLabellogoutMouseEntered

    private void jLabellogoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabellogoutMouseExited
        jLabellogout.setBackground(new Color(53, 59, 72));
    }//GEN-LAST:event_jLabellogoutMouseExited

    private void jLabelsettingsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelsettingsMouseClicked

        settings settings = new settings();
        settings.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabelsettingsMouseClicked

    private void jLabelsettingsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelsettingsMouseEntered
        jLabelsettings.setBackground(new Color(39, 60, 117));
    }//GEN-LAST:event_jLabelsettingsMouseEntered

    private void jLabelsettingsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelsettingsMouseExited
        jLabelsettings.setBackground(new Color(53, 59, 72));
    }//GEN-LAST:event_jLabelsettingsMouseExited

    private void jLabelhelpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelhelpMouseClicked

        help help = new help();
        help.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabelhelpMouseClicked

    private void jLabelhelpMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelhelpMouseEntered
        jLabelhelp.setBackground(new Color(39, 60, 117));
    }//GEN-LAST:event_jLabelhelpMouseEntered

    private void jLabelhelpMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelhelpMouseExited
        jLabelhelp.setBackground(new Color(53, 59, 72));
    }//GEN-LAST:event_jLabelhelpMouseExited

    private void jLabelhomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelhomeMouseClicked
        home home = new home();
        home.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabelhomeMouseClicked

    private void jLabelhomeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelhomeMouseEntered
        jLabelhome.setBackground(new Color(39, 60, 117));
    }//GEN-LAST:event_jLabelhomeMouseEntered

    private void jLabelhomeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelhomeMouseExited
        jLabelhome.setBackground(new Color(53, 59, 72));
    }//GEN-LAST:event_jLabelhomeMouseExited

    private void jLabelemergencymenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelemergencymenuMouseClicked

        emergency emergency = new emergency();
        emergency.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabelemergencymenuMouseClicked

    private void jLabelemergencymenuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelemergencymenuMouseEntered
        jLabelemergencymenu.setBackground(new Color(39, 60, 117));
    }//GEN-LAST:event_jLabelemergencymenuMouseEntered

    private void jLabelemergencymenuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelemergencymenuMouseExited
        jLabelemergencymenu.setBackground(new Color(53, 59, 72));
    }//GEN-LAST:event_jLabelemergencymenuMouseExited

    private void jLabelreportmenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelreportmenuMouseClicked

        report report = new report();
        report.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabelreportmenuMouseClicked

    private void jLabelreportmenuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelreportmenuMouseEntered
        jLabelreportmenu.setBackground(new Color(39, 60, 117));
    }//GEN-LAST:event_jLabelreportmenuMouseEntered

    private void jLabelreportmenuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelreportmenuMouseExited
        jLabelreportmenu.setBackground(new Color(53, 59, 72));
    }//GEN-LAST:event_jLabelreportmenuMouseExited

    private void jLabelgovinfomenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelgovinfomenuMouseClicked

        govinfo govinfo = new govinfo();
        govinfo.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabelgovinfomenuMouseClicked

    private void jLabelgovinfomenuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelgovinfomenuMouseEntered
        jLabelgovinfomenu.setBackground(new Color(39, 60, 117));
    }//GEN-LAST:event_jLabelgovinfomenuMouseEntered

    private void jLabelgovinfomenuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelgovinfomenuMouseExited
        jLabelgovinfomenu.setBackground(new Color(53, 59, 72));
    }//GEN-LAST:event_jLabelgovinfomenuMouseExited

    private void jLabelfeedbackmenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelfeedbackmenuMouseClicked

        feedback feedback = new feedback();
        feedback.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabelfeedbackmenuMouseClicked

    private void jLabelfeedbackmenuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelfeedbackmenuMouseEntered
        jLabelfeedbackmenu.setBackground(new Color(39, 60, 117));
    }//GEN-LAST:event_jLabelfeedbackmenuMouseEntered

    private void jLabelfeedbackmenuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelfeedbackmenuMouseExited
        jLabelfeedbackmenu.setBackground(new Color(53, 59, 72));
    }//GEN-LAST:event_jLabelfeedbackmenuMouseExited

    private void jLabelsettingsmenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelsettingsmenuMouseClicked

        settings settings = new settings();
        settings.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabelsettingsmenuMouseClicked

    private void jLabelsettingsmenuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelsettingsmenuMouseEntered
        jLabelsettingsmenu.setBackground(new Color(39, 60, 117));
    }//GEN-LAST:event_jLabelsettingsmenuMouseEntered

    private void jLabelsettingsmenuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelsettingsmenuMouseExited
        jLabelsettingsmenu.setBackground(new Color(53, 59, 72));
    }//GEN-LAST:event_jLabelsettingsmenuMouseExited

    private void jLabelsupportmenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelsupportmenuMouseClicked

        help help = new help();
        help.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabelsupportmenuMouseClicked

    private void jLabelsupportmenuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelsupportmenuMouseEntered
        jLabelsupportmenu.setBackground(new Color(39, 60, 117));
    }//GEN-LAST:event_jLabelsupportmenuMouseEntered

    private void jLabelsupportmenuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelsupportmenuMouseExited
        jLabelsupportmenu.setBackground(new Color(53, 59, 72));
    }//GEN-LAST:event_jLabelsupportmenuMouseExited

    private void jLabellogoutmenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabellogoutmenuMouseClicked

        login login = new login();
        login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabellogoutmenuMouseClicked

    private void jLabellogoutmenuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabellogoutmenuMouseEntered
        jLabellogoutmenu.setBackground(new Color(39, 60, 117));
    }//GEN-LAST:event_jLabellogoutmenuMouseEntered

    private void jLabellogoutmenuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabellogoutmenuMouseExited
        jLabellogoutmenu.setBackground(new Color(53, 59, 72));
    }//GEN-LAST:event_jLabellogoutmenuMouseExited

    private void jLabelbackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelbackMouseClicked
        jLabelmenu.setVisible(true);
        jPanelmenu.setVisible(false);
    }//GEN-LAST:event_jLabelbackMouseClicked

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        KIND = (String) jComboBox1.getSelectedItem();
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed

        String DESCRIPTION = jTextArea2.getText();
        String SUGGESTION = jTextArea1.getText();
        String LINK = jTextField1.getText();

        if (TYPE.isEmpty() || KIND.isEmpty() || DESCRIPTION.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Fields are Empty");
        } else {

            try {
                DatabaseOperation operation1 = new DatabaseOperation();
                operation1.connect();
                operation1.setData_report(login.USERID,TYPE, KIND, DESCRIPTION, SUGGESTION, LINK);
          }
           catch (Exception e) {
                JOptionPane.showMessageDialog(null, e.toString());
            }
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void giveadviceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_giveadviceActionPerformed
        if (giveadvice.isSelected()) {
            reportproblem.setSelected(false);
            TYPE = "give advice";

        }
    }//GEN-LAST:event_giveadviceActionPerformed

    private void reportproblemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reportproblemActionPerformed
        if (reportproblem.isSelected()) {
            giveadvice.setSelected(false);
            TYPE = "report problem";

        }
    }//GEN-LAST:event_reportproblemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(report.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(report.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(report.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(report.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new report().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bangladesh;
    private javax.swing.JRadioButton giveadvice;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabeMin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelClose;
    private javax.swing.JLabel jLabelback;
    private javax.swing.JLabel jLabelemergencymenu;
    private javax.swing.JLabel jLabelfeedbackmenu;
    private javax.swing.JLabel jLabelgovinfomenu;
    private javax.swing.JLabel jLabelhelp;
    private javax.swing.JLabel jLabelhome;
    private javax.swing.JLabel jLabellogout;
    private javax.swing.JLabel jLabellogoutmenu;
    private javax.swing.JLabel jLabelmenu;
    private javax.swing.JLabel jLabelreportmenu;
    private javax.swing.JLabel jLabelsettings;
    private javax.swing.JLabel jLabelsettingsmenu;
    private javax.swing.JLabel jLabelsupportmenu;
    private javax.swing.JLabel jLabeluser;
    private javax.swing.JPanel jPanelmenu;
    private javax.swing.JPanel jPanelpersonal;
    private javax.swing.JPanel jPanelreport;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JRadioButton reportproblem;
    // End of variables declaration//GEN-END:variables
}
