/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hello_bangladesh;
import java.awt.Color;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Asus
 */
public class settings extends javax.swing.JFrame {

    ImageIcon ii,icon;
    
    private String Name,NID,PresentAddress,PassportNo,MobileNo,OldPass,NewPass,Password,ConfirmPass;
    public settings() {
        initComponents();
        
          pack();
         icon = new ImageIcon(getClass().getResource("image\\bangladesh map_316px.png"));
         setIconImage(icon.getImage()); // set java frame icon
         setLocationRelativeTo(null);
        setBackground(new Color(0,0,0,0)); 
        jPanelsettings.setBackground(new Color(53,59,72,230));
        //bangladesh.setBackground(new Color(0,0,0,55));
        jPanelmenu.setVisible(false);
       // jPanelmenu.setBackground(new Color(53,59,72,100));
        jPanelpersonal.setVisible(false);
        jPanelpersonal.setBackground(new Color(53,59,72,100));
        
        DatabaseOperation ob=new DatabaseOperation();
        ob.connect();
        NID=login.USERID;
        Password=login.Password;
        String info[]=ob.getInfo(NID);
        Name=info[0];
        PassportNo=info[1];
        PresentAddress=info[2];
        MobileNo=info[3];
        Password=info[4];
       jTextField3.setText(Name);
       jTextField3.setEditable(false);
       jTextField5.setText(NID);
       jTextField5.setEditable(false);
       jTextField6.setText(PassportNo);
       jTextField6.setEditable(false);
       jTextField2.setText(MobileNo);
       jTextArea5.setText(PresentAddress);
       try{
       ImageIcon image = new ImageIcon(ob.displayImage(NID));
       Image im = image.getImage();
       Image myImg = im.getScaledInstance(jLabel1.getWidth(), jLabel1.getHeight(),Image.SCALE_SMOOTH);
       ImageIcon newImage = new ImageIcon(myImg);
       jLabel1.setIcon(newImage);
       }
       catch(Exception e)
       {
           JOptionPane.showMessageDialog(null, "No Data");     
       }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelpersonal = new javax.swing.JPanel();
        jLabellogout = new javax.swing.JLabel();
        jLabelsettings = new javax.swing.JLabel();
        jLabelhelp = new javax.swing.JLabel();
        jPanelmenu = new javax.swing.JPanel();
        jLabelhome = new javax.swing.JLabel();
        jLabelemergencymenu = new javax.swing.JLabel();
        jLabelreportmenu = new javax.swing.JLabel();
        jLabelgovinfomenu = new javax.swing.JLabel();
        jLabelfeedbackmenu = new javax.swing.JLabel();
        jLabelsettingsmenu = new javax.swing.JLabel();
        jLabelsupportmenu = new javax.swing.JLabel();
        jLabellogoutmenu = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabelback = new javax.swing.JLabel();
        jPanelsettings = new javax.swing.JPanel();
        jLabeluser = new javax.swing.JLabel();
        jLabelClose = new javax.swing.JLabel();
        jLabeMin = new javax.swing.JLabel();
        jLabelmenu = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextArea5 = new javax.swing.JTextArea();
        jLabel16 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jPasswordField1 = new javax.swing.JPasswordField();
        jSeparator10 = new javax.swing.JSeparator();
        jPasswordField2 = new javax.swing.JPasswordField();
        jPasswordField3 = new javax.swing.JPasswordField();
        jButton5 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        bangladesh = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelpersonal.setBackground(new java.awt.Color(53, 59, 73));
        jPanelpersonal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabellogout.setBackground(new java.awt.Color(52, 59, 72));
        jLabellogout.setForeground(new java.awt.Color(255, 255, 255));
        jLabellogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hello_bangladesh/image/logout.png"))); // NOI18N
        jLabellogout.setText("Log Out");
        jLabellogout.setOpaque(true);
        jLabellogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabellogoutMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabellogoutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabellogoutMouseExited(evt);
            }
        });
        jPanelpersonal.add(jLabellogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 90, 20));

        jLabelsettings.setBackground(new java.awt.Color(52, 59, 72));
        jLabelsettings.setForeground(new java.awt.Color(255, 255, 255));
        jLabelsettings.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hello_bangladesh/image/settings.png"))); // NOI18N
        jLabelsettings.setText("Settings");
        jLabelsettings.setOpaque(true);
        jLabelsettings.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelsettingsMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelsettingsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelsettingsMouseExited(evt);
            }
        });
        jPanelpersonal.add(jLabelsettings, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 90, 20));

        jLabelhelp.setBackground(new java.awt.Color(52, 59, 72));
        jLabelhelp.setForeground(new java.awt.Color(255, 255, 255));
        jLabelhelp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hello_bangladesh/image/help.png"))); // NOI18N
        jLabelhelp.setText("Help");
        jLabelhelp.setOpaque(true);
        jLabelhelp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelhelpMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelhelpMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelhelpMouseExited(evt);
            }
        });
        jPanelpersonal.add(jLabelhelp, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 90, 20));

        getContentPane().add(jPanelpersonal, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 40, 90, 60));

        jPanelmenu.setBackground(new java.awt.Color(53, 59, 73));
        jPanelmenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelhome.setBackground(new java.awt.Color(52, 59, 72));
        jLabelhome.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelhome.setForeground(new java.awt.Color(255, 255, 255));
        jLabelhome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hello_bangladesh/image/home_30px.png"))); // NOI18N
        jLabelhome.setText("Home");
        jLabelhome.setOpaque(true);
        jLabelhome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelhomeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelhomeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelhomeMouseExited(evt);
            }
        });
        jPanelmenu.add(jLabelhome, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 240, -1));

        jLabelemergencymenu.setBackground(new java.awt.Color(52, 59, 72));
        jLabelemergencymenu.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelemergencymenu.setForeground(new java.awt.Color(255, 255, 255));
        jLabelemergencymenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hello_bangladesh/image/emergency_30px.png"))); // NOI18N
        jLabelemergencymenu.setText("Emergency Service");
        jLabelemergencymenu.setOpaque(true);
        jLabelemergencymenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelemergencymenuMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelemergencymenuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelemergencymenuMouseExited(evt);
            }
        });
        jPanelmenu.add(jLabelemergencymenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 240, 30));

        jLabelreportmenu.setBackground(new java.awt.Color(52, 59, 72));
        jLabelreportmenu.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelreportmenu.setForeground(new java.awt.Color(255, 255, 255));
        jLabelreportmenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hello_bangladesh/image/report_30px.png"))); // NOI18N
        jLabelreportmenu.setText("Report");
        jLabelreportmenu.setOpaque(true);
        jLabelreportmenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelreportmenuMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelreportmenuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelreportmenuMouseExited(evt);
            }
        });
        jPanelmenu.add(jLabelreportmenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 240, -1));

        jLabelgovinfomenu.setBackground(new java.awt.Color(52, 59, 72));
        jLabelgovinfomenu.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelgovinfomenu.setForeground(new java.awt.Color(255, 255, 255));
        jLabelgovinfomenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hello_bangladesh/image/info_30px.png"))); // NOI18N
        jLabelgovinfomenu.setText("Gov. Info");
        jLabelgovinfomenu.setOpaque(true);
        jLabelgovinfomenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelgovinfomenuMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelgovinfomenuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelgovinfomenuMouseExited(evt);
            }
        });
        jPanelmenu.add(jLabelgovinfomenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 240, 30));

        jLabelfeedbackmenu.setBackground(new java.awt.Color(52, 59, 72));
        jLabelfeedbackmenu.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelfeedbackmenu.setForeground(new java.awt.Color(255, 255, 255));
        jLabelfeedbackmenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hello_bangladesh/image/Feedback_30px.png"))); // NOI18N
        jLabelfeedbackmenu.setText("Feedback");
        jLabelfeedbackmenu.setOpaque(true);
        jLabelfeedbackmenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelfeedbackmenuMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelfeedbackmenuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelfeedbackmenuMouseExited(evt);
            }
        });
        jPanelmenu.add(jLabelfeedbackmenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 240, 30));

        jLabelsettingsmenu.setBackground(new java.awt.Color(52, 59, 72));
        jLabelsettingsmenu.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelsettingsmenu.setForeground(new java.awt.Color(255, 255, 255));
        jLabelsettingsmenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hello_bangladesh/image/Settings_30px.png"))); // NOI18N
        jLabelsettingsmenu.setText("Settings");
        jLabelsettingsmenu.setOpaque(true);
        jLabelsettingsmenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelsettingsmenuMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelsettingsmenuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelsettingsmenuMouseExited(evt);
            }
        });
        jPanelmenu.add(jLabelsettingsmenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 290, 240, 30));

        jLabelsupportmenu.setBackground(new java.awt.Color(52, 59, 72));
        jLabelsupportmenu.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelsupportmenu.setForeground(new java.awt.Color(255, 255, 255));
        jLabelsupportmenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hello_bangladesh/image/Customer_Support_30px.png"))); // NOI18N
        jLabelsupportmenu.setText("Help & Support");
        jLabelsupportmenu.setOpaque(true);
        jLabelsupportmenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelsupportmenuMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelsupportmenuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelsupportmenuMouseExited(evt);
            }
        });
        jPanelmenu.add(jLabelsupportmenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 330, 240, -1));

        jLabellogoutmenu.setBackground(new java.awt.Color(52, 59, 72));
        jLabellogoutmenu.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabellogoutmenu.setForeground(new java.awt.Color(255, 255, 255));
        jLabellogoutmenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hello_bangladesh/image/logout_30px.png"))); // NOI18N
        jLabellogoutmenu.setText("Log Out");
        jLabellogoutmenu.setOpaque(true);
        jLabellogoutmenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabellogoutmenuMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabellogoutmenuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabellogoutmenuMouseExited(evt);
            }
        });
        jPanelmenu.add(jLabellogoutmenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 370, 240, 30));
        jPanelmenu.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 240, 10));

        jLabelback.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hello_bangladesh/image/Back_Arrow_30px.png"))); // NOI18N
        jLabelback.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelbackMouseClicked(evt);
            }
        });
        jPanelmenu.add(jLabelback, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 10, -1, -1));

        getContentPane().add(jPanelmenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 600));

        jPanelsettings.setBackground(new java.awt.Color(53, 59, 72));
        jPanelsettings.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanelsettingsMouseDragged(evt);
            }
        });
        jPanelsettings.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelsettingsMouseClicked(evt);
            }
        });
        jPanelsettings.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabeluser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hello_bangladesh/image/user.png"))); // NOI18N
        jLabeluser.setFocusable(false);
        jLabeluser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabeluserMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabeluserMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabeluserMouseExited(evt);
            }
        });
        jPanelsettings.add(jLabeluser, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 10, -1, -1));

        jLabelClose.setFont(new java.awt.Font("Adobe Devanagari", 0, 18)); // NOI18N
        jLabelClose.setForeground(new java.awt.Color(255, 0, 0));
        jLabelClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hello_bangladesh/image/close.png"))); // NOI18N
        jLabelClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelCloseMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelCloseMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelCloseMouseExited(evt);
            }
        });
        jPanelsettings.add(jLabelClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 10, 20, 20));

        jLabeMin.setFont(new java.awt.Font("Adobe Devanagari", 1, 24)); // NOI18N
        jLabeMin.setForeground(new java.awt.Color(255, 255, 102));
        jLabeMin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hello_bangladesh/image/minimize.png"))); // NOI18N
        jLabeMin.setToolTipText("");
        jLabeMin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabeMinMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabeMinMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabeMinMouseExited(evt);
            }
        });
        jPanelsettings.add(jLabeMin, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 10, 20, -1));

        jLabelmenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hello_bangladesh/image/menu.png"))); // NOI18N
        jLabelmenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelmenuMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelmenuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelmenuMouseExited(evt);
            }
        });
        jPanelsettings.add(jLabelmenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 30));

        jLabel9.setFont(new java.awt.Font("Book Antiqua", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Name :");
        jPanelsettings.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, 60, 20));

        jLabel6.setFont(new java.awt.Font("Book Antiqua", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("NID  :");
        jPanelsettings.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, 50, 20));

        jLabel8.setFont(new java.awt.Font("Book Antiqua", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Present Address :");
        jPanelsettings.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 240, -1, 20));

        jTextArea5.setBackground(new java.awt.Color(53, 59, 72));
        jTextArea5.setColumns(20);
        jTextArea5.setFont(new java.awt.Font("Book Antiqua", 0, 18)); // NOI18N
        jTextArea5.setForeground(new java.awt.Color(255, 255, 255));
        jTextArea5.setRows(5);
        jScrollPane4.setViewportView(jTextArea5);

        jPanelsettings.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 230, 370, 80));

        jLabel16.setFont(new java.awt.Font("Book Antiqua", 0, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Passport No:");
        jPanelsettings.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 140, -1, -1));

        jLabel12.setFont(new java.awt.Font("Book Antiqua", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Mobile no :");
        jPanelsettings.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 180, -1, -1));

        jLabel2.setFont(new java.awt.Font("Book Antiqua", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Want to change password ?");
        jPanelsettings.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 370, -1, -1));

        jLabel3.setFont(new java.awt.Font("Book Antiqua", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Confirm Password :");
        jPanelsettings.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 500, -1, -1));

        jLabel4.setFont(new java.awt.Font("Book Antiqua", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Old Password :");
        jPanelsettings.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 420, -1, -1));

        jLabel5.setFont(new java.awt.Font("Book Antiqua", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("New Password :");
        jPanelsettings.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 460, -1, -1));

        jTextField2.setBackground(new java.awt.Color(53, 59, 72));
        jTextField2.setFont(new java.awt.Font("Aharoni", 0, 18)); // NOI18N
        jTextField2.setForeground(new java.awt.Color(204, 204, 255));
        jTextField2.setText("Enter your name");
        jTextField2.setBorder(null);
        jTextField2.setCaretColor(new java.awt.Color(255, 255, 255));
        jTextField2.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        jTextField2.setOpaque(false);
        jTextField2.setSelectionColor(new java.awt.Color(255, 255, 255));
        jTextField2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField2FocusGained(evt);
            }
        });
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        jPanelsettings.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 180, 340, 20));

        jTextField3.setBackground(new java.awt.Color(53, 59, 72));
        jTextField3.setFont(new java.awt.Font("Aharoni", 0, 18)); // NOI18N
        jTextField3.setForeground(new java.awt.Color(204, 204, 255));
        jTextField3.setText("Enter your name");
        jTextField3.setBorder(null);
        jTextField3.setCaretColor(new java.awt.Color(255, 255, 255));
        jTextField3.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        jTextField3.setOpaque(false);
        jTextField3.setSelectionColor(new java.awt.Color(255, 255, 255));
        jTextField3.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField3FocusGained(evt);
            }
        });
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        jPanelsettings.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 60, 340, 20));

        jTextField5.setBackground(new java.awt.Color(53, 59, 72));
        jTextField5.setFont(new java.awt.Font("Aharoni", 0, 18)); // NOI18N
        jTextField5.setForeground(new java.awt.Color(204, 204, 255));
        jTextField5.setText("Enter your name");
        jTextField5.setBorder(null);
        jTextField5.setCaretColor(new java.awt.Color(255, 255, 255));
        jTextField5.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        jTextField5.setOpaque(false);
        jTextField5.setSelectionColor(new java.awt.Color(255, 255, 255));
        jTextField5.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField5FocusGained(evt);
            }
        });
        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });
        jPanelsettings.add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 100, 340, 20));

        jTextField6.setBackground(new java.awt.Color(53, 59, 72));
        jTextField6.setFont(new java.awt.Font("Aharoni", 0, 18)); // NOI18N
        jTextField6.setForeground(new java.awt.Color(204, 204, 255));
        jTextField6.setText("Enter your name");
        jTextField6.setBorder(null);
        jTextField6.setCaretColor(new java.awt.Color(255, 255, 255));
        jTextField6.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        jTextField6.setOpaque(false);
        jTextField6.setSelectionColor(new java.awt.Color(255, 255, 255));
        jTextField6.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField6FocusGained(evt);
            }
        });
        jTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField6ActionPerformed(evt);
            }
        });
        jPanelsettings.add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 140, 340, 20));

        jPasswordField1.setBackground(new java.awt.Color(53, 59, 72));
        jPasswordField1.setForeground(new java.awt.Color(204, 204, 255));
        jPasswordField1.setText("Enter your password");
        jPasswordField1.setBorder(null);
        jPasswordField1.setOpaque(false);
        jPasswordField1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jPasswordField1FocusGained(evt);
            }
        });
        jPasswordField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField1ActionPerformed(evt);
            }
        });
        jPanelsettings.add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 500, 290, 20));

        jSeparator10.setForeground(new java.awt.Color(255, 204, 102));
        jPanelsettings.add(jSeparator10, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 340, 700, 20));

        jPasswordField2.setBackground(new java.awt.Color(53, 59, 72));
        jPasswordField2.setForeground(new java.awt.Color(204, 204, 255));
        jPasswordField2.setText("Enter your password");
        jPasswordField2.setBorder(null);
        jPasswordField2.setOpaque(false);
        jPasswordField2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jPasswordField2FocusGained(evt);
            }
        });
        jPasswordField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField2ActionPerformed(evt);
            }
        });
        jPanelsettings.add(jPasswordField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 420, 290, -1));

        jPasswordField3.setBackground(new java.awt.Color(53, 59, 72));
        jPasswordField3.setForeground(new java.awt.Color(204, 204, 255));
        jPasswordField3.setText("Enter your password");
        jPasswordField3.setBorder(null);
        jPasswordField3.setOpaque(false);
        jPasswordField3.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jPasswordField3FocusGained(evt);
            }
        });
        jPasswordField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField3ActionPerformed(evt);
            }
        });
        jPanelsettings.add(jPasswordField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 460, 290, 20));

        jButton5.setBackground(new java.awt.Color(53, 59, 72));
        jButton5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("Done");
        jButton5.setBorder(null);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanelsettings.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 520, 120, 30));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hello_bangladesh/image/person-icon.png"))); // NOI18N
        jPanelsettings.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 70, 150, 170));

        getContentPane().add(jPanelsettings, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1050, 600));

        bangladesh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hello_bangladesh/bangladesh map.png"))); // NOI18N
        getContentPane().add(bangladesh, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelhomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelhomeMouseClicked
        home home = new home();
        home.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabelhomeMouseClicked

    private void jLabelhomeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelhomeMouseEntered
        jLabelhome.setBackground(new Color(39,60,117));
    }//GEN-LAST:event_jLabelhomeMouseEntered

    private void jLabelhomeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelhomeMouseExited
        jLabelhome.setBackground(new Color(53,59,72));
    }//GEN-LAST:event_jLabelhomeMouseExited

    private void jLabelemergencymenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelemergencymenuMouseClicked

        emergency emergency = new emergency();
        emergency.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabelemergencymenuMouseClicked

    private void jLabelemergencymenuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelemergencymenuMouseEntered
        jLabelemergencymenu.setBackground(new Color(39,60,117));
    }//GEN-LAST:event_jLabelemergencymenuMouseEntered

    private void jLabelemergencymenuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelemergencymenuMouseExited
        jLabelemergencymenu.setBackground(new Color(53,59,72));
    }//GEN-LAST:event_jLabelemergencymenuMouseExited

    private void jLabelreportmenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelreportmenuMouseClicked

        report report = new report();
        report.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabelreportmenuMouseClicked

    private void jLabelreportmenuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelreportmenuMouseEntered
        jLabelreportmenu.setBackground(new Color(39,60,117));
    }//GEN-LAST:event_jLabelreportmenuMouseEntered

    private void jLabelreportmenuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelreportmenuMouseExited
        jLabelreportmenu.setBackground(new Color(53,59,72));
    }//GEN-LAST:event_jLabelreportmenuMouseExited

    private void jLabelgovinfomenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelgovinfomenuMouseClicked

        govinfo govinfo = new govinfo();
        govinfo.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabelgovinfomenuMouseClicked

    private void jLabelgovinfomenuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelgovinfomenuMouseEntered
        jLabelgovinfomenu.setBackground(new Color(39,60,117));
    }//GEN-LAST:event_jLabelgovinfomenuMouseEntered

    private void jLabelgovinfomenuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelgovinfomenuMouseExited
        jLabelgovinfomenu.setBackground(new Color(53,59,72));
    }//GEN-LAST:event_jLabelgovinfomenuMouseExited

    private void jLabelfeedbackmenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelfeedbackmenuMouseClicked

        feedback feedback = new feedback();
        feedback.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabelfeedbackmenuMouseClicked

    private void jLabelfeedbackmenuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelfeedbackmenuMouseEntered
        jLabelfeedbackmenu.setBackground(new Color(39,60,117));
    }//GEN-LAST:event_jLabelfeedbackmenuMouseEntered

    private void jLabelfeedbackmenuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelfeedbackmenuMouseExited
        jLabelfeedbackmenu.setBackground(new Color(53,59,72));
    }//GEN-LAST:event_jLabelfeedbackmenuMouseExited

    private void jLabelsettingsmenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelsettingsmenuMouseClicked

        settings settings = new settings();
        settings.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabelsettingsmenuMouseClicked

    private void jLabelsettingsmenuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelsettingsmenuMouseEntered
        jLabelsettingsmenu.setBackground(new Color(39,60,117));
    }//GEN-LAST:event_jLabelsettingsmenuMouseEntered

    private void jLabelsettingsmenuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelsettingsmenuMouseExited
        jLabelsettingsmenu.setBackground(new Color(53,59,72));
    }//GEN-LAST:event_jLabelsettingsmenuMouseExited

    private void jLabelsupportmenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelsupportmenuMouseClicked

        help help = new help();
        help.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabelsupportmenuMouseClicked

    private void jLabelsupportmenuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelsupportmenuMouseEntered
        jLabelsupportmenu.setBackground(new Color(39,60,117));
    }//GEN-LAST:event_jLabelsupportmenuMouseEntered

    private void jLabelsupportmenuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelsupportmenuMouseExited
        jLabelsupportmenu.setBackground(new Color(53,59,72));
    }//GEN-LAST:event_jLabelsupportmenuMouseExited

    private void jLabellogoutmenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabellogoutmenuMouseClicked

        login login = new login();
        login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabellogoutmenuMouseClicked

    private void jLabellogoutmenuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabellogoutmenuMouseEntered
        jLabellogoutmenu.setBackground(new Color(39,60,117));
    }//GEN-LAST:event_jLabellogoutmenuMouseEntered

    private void jLabellogoutmenuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabellogoutmenuMouseExited
        jLabellogoutmenu.setBackground(new Color(53,59,72));
    }//GEN-LAST:event_jLabellogoutmenuMouseExited

    private void jLabelbackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelbackMouseClicked
        jLabelmenu.setVisible(true);
        jPanelmenu.setVisible(false);
    }//GEN-LAST:event_jLabelbackMouseClicked

    private void jLabellogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabellogoutMouseClicked

        login login = new login();
        login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabellogoutMouseClicked

    private void jLabellogoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabellogoutMouseEntered
        jLabellogout.setBackground(new Color(39,60,117));
    }//GEN-LAST:event_jLabellogoutMouseEntered

    private void jLabellogoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabellogoutMouseExited
        jLabellogout.setBackground(new Color(53,59,72));
    }//GEN-LAST:event_jLabellogoutMouseExited

    private void jLabelsettingsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelsettingsMouseClicked

        settings settings = new settings();
        settings.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabelsettingsMouseClicked

    private void jLabelsettingsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelsettingsMouseEntered
        jLabelsettings.setBackground(new Color(39,60,117));
    }//GEN-LAST:event_jLabelsettingsMouseEntered

    private void jLabelsettingsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelsettingsMouseExited
        jLabelsettings.setBackground(new Color(53,59,72));
    }//GEN-LAST:event_jLabelsettingsMouseExited

    private void jLabelhelpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelhelpMouseClicked

        help help = new help();
        help.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabelhelpMouseClicked

    private void jLabelhelpMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelhelpMouseEntered
        jLabelhelp.setBackground(new Color(39,60,117));
    }//GEN-LAST:event_jLabelhelpMouseEntered

    private void jLabelhelpMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelhelpMouseExited
        jLabelhelp.setBackground(new Color(53,59,72));
    }//GEN-LAST:event_jLabelhelpMouseExited

    private void jLabeluserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabeluserMouseClicked
        jPanelpersonal.setVisible(true);
    }//GEN-LAST:event_jLabeluserMouseClicked

    private void jLabeluserMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabeluserMouseEntered
        ii = new ImageIcon(getClass().getResource("image\\user1.png"));
        jLabeluser.setIcon(ii);
    }//GEN-LAST:event_jLabeluserMouseEntered

    private void jLabeluserMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabeluserMouseExited
        ii = new ImageIcon(getClass().getResource("image\\user.png"));
        jLabeluser.setIcon(ii);
    }//GEN-LAST:event_jLabeluserMouseExited

    private void jLabelCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelCloseMouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabelCloseMouseClicked

    private void jLabelCloseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelCloseMouseEntered
        ii = new ImageIcon(getClass().getResource("image\\close1.png"));
        jLabelClose.setIcon(ii);
    }//GEN-LAST:event_jLabelCloseMouseEntered

    private void jLabelCloseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelCloseMouseExited
        ii = new ImageIcon(getClass().getResource("image\\close.png"));
        jLabelClose.setIcon(ii);
    }//GEN-LAST:event_jLabelCloseMouseExited

    private void jLabeMinMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabeMinMouseClicked
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_jLabeMinMouseClicked

    private void jLabeMinMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabeMinMouseEntered
        ii = new ImageIcon(getClass().getResource("image\\minimize1.png"));
        jLabeMin.setIcon(ii);
    }//GEN-LAST:event_jLabeMinMouseEntered

    private void jLabeMinMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabeMinMouseExited
        ii = new ImageIcon(getClass().getResource("image\\minimize.png"));
        jLabeMin.setIcon(ii);
    }//GEN-LAST:event_jLabeMinMouseExited

    private void jLabelmenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelmenuMouseClicked

        jPanelmenu.setVisible(true);
        jLabelmenu.setVisible(false);
    }//GEN-LAST:event_jLabelmenuMouseClicked

    private void jLabelmenuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelmenuMouseEntered
        ii = new ImageIcon(getClass().getResource("image\\menu1.png"));
        jLabelmenu.setIcon(ii);
    }//GEN-LAST:event_jLabelmenuMouseEntered

    private void jLabelmenuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelmenuMouseExited
        ii = new ImageIcon(getClass().getResource("image\\menu.png"));
        jLabelmenu.setIcon(ii);
    }//GEN-LAST:event_jLabelmenuMouseExited

    private void jPanelsettingsMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelsettingsMouseDragged
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanelsettingsMouseDragged

    private void jPanelsettingsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelsettingsMouseClicked
        jPanelmenu.setVisible(false);
        jLabelmenu.setVisible(true);
        jPanelpersonal.setVisible(false);
    }//GEN-LAST:event_jPanelsettingsMouseClicked

    private void jTextField2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField2FocusGained
        jTextField2.setText("");
    }//GEN-LAST:event_jTextField2FocusGained

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jTextField3FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField3FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3FocusGained

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jTextField5FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField5FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5FocusGained

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void jTextField6FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField6FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField6FocusGained

    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField6ActionPerformed

    private void jPasswordField1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPasswordField1FocusGained
        jPasswordField1.setText("");
    }//GEN-LAST:event_jPasswordField1FocusGained

    private void jPasswordField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField1ActionPerformed

    private void jPasswordField2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPasswordField2FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField2FocusGained

    private void jPasswordField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField2ActionPerformed

    private void jPasswordField3FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPasswordField3FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField3FocusGained

    private void jPasswordField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
       Name=jTextField3.getText();
       NID=jTextField5.getText();
      PassportNo=jTextField6.getText();
      MobileNo=jTextField2.getText();
      PresentAddress=jTextArea5.getText();
       OldPass=new String(jPasswordField2.getPassword());
       NewPass=new String(jPasswordField3.getPassword());
       ConfirmPass=new String(jPasswordField1.getPassword());
       if(OldPass.equals(Password))
       {
          
           if(NewPass.equals(ConfirmPass))
           {
              
            DatabaseOperation ob=new DatabaseOperation();
            ob.connect();
            try{
            ob.updateData(NID, PresentAddress, MobileNo, NewPass);
             this.dispose();
            home homepage=new home();
            homepage.setVisible(true);
             }
           
            catch(Exception e)
            {
               JOptionPane.showMessageDialog(null,e.getMessage());
               
            }
           }
       else
            System.out.println("Not Matched");
    }//GEN-LAST:event_jButton5ActionPerformed

       else
            System.out.println("Not Matched");
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(settings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(settings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(settings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(settings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new settings().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bangladesh;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabeMin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelClose;
    private javax.swing.JLabel jLabelback;
    private javax.swing.JLabel jLabelemergencymenu;
    private javax.swing.JLabel jLabelfeedbackmenu;
    private javax.swing.JLabel jLabelgovinfomenu;
    private javax.swing.JLabel jLabelhelp;
    private javax.swing.JLabel jLabelhome;
    private javax.swing.JLabel jLabellogout;
    private javax.swing.JLabel jLabellogoutmenu;
    private javax.swing.JLabel jLabelmenu;
    private javax.swing.JLabel jLabelreportmenu;
    private javax.swing.JLabel jLabelsettings;
    private javax.swing.JLabel jLabelsettingsmenu;
    private javax.swing.JLabel jLabelsupportmenu;
    private javax.swing.JLabel jLabeluser;
    private javax.swing.JPanel jPanelmenu;
    private javax.swing.JPanel jPanelpersonal;
    private javax.swing.JPanel jPanelsettings;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JPasswordField jPasswordField2;
    private javax.swing.JPasswordField jPasswordField3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JTextArea jTextArea5;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    // End of variables declaration//GEN-END:variables
}
