/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hello_bangladesh;

import java.awt.Color;
import java.awt.GraphicsEnvironment;
import java.io.File;
import java.text.DateFormat;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author joyultimates
 */
public class signup extends javax.swing.JFrame  {

    ImageIcon ii,icon;
    String Gender;
    File image1,image2;
    ImageOperation io= new ImageOperation();
     static boolean maximized = true;
     
     
    public signup() {
        initComponents();
         icon = new ImageIcon(getClass().getResource("image\\bangladesh map_316px.png"));
         setIconImage(icon.getImage()); // set java frame icon
        setLocationRelativeTo(null);
        setBackground(new Color(0,0,0,0));  // to make background transparent
        jPanel1.setBackground(new Color(53,59,72,230));

    }
    
  
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jPanel1 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JSeparator();
        jLabel13 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jRadioButton1 = new javax.swing.JRadioButton();
        jLabel10 = new javax.swing.JLabel();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();
        jCheckBox3 = new javax.swing.JCheckBox();
        jCheckBox5 = new javax.swing.JCheckBox();
        jCheckBox6 = new javax.swing.JCheckBox();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextArea5 = new javax.swing.JTextArea();
        jLabel15 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea4 = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel17 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jSeparator7 = new javax.swing.JSeparator();
        jLabel18 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        jSeparator8 = new javax.swing.JSeparator();
        jLabel12 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jSeparator9 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        jSeparator10 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        jLabeMin = new javax.swing.JLabel();
        jLabelClose = new javax.swing.JLabel();
        bangladesh = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(53, 59, 72));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Book Antiqua", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Name :");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        jTextField2.setBackground(new java.awt.Color(53, 59, 72));
        jTextField2.setFont(new java.awt.Font("Aharoni", 0, 12)); // NOI18N
        jTextField2.setForeground(new java.awt.Color(204, 204, 255));
        jTextField2.setText("Enter your name");
        jTextField2.setBorder(null);
        jTextField2.setCaretColor(new java.awt.Color(255, 255, 255));
        jTextField2.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        jTextField2.setOpaque(false);
        jTextField2.setSelectionColor(new java.awt.Color(255, 255, 255));
        jTextField2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField2FocusGained(evt);
            }
        });
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 290, 30));

        jSeparator5.setForeground(new java.awt.Color(255, 204, 102));
        jPanel1.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 290, 20));

        jLabel7.setFont(new java.awt.Font("Book Antiqua", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Father's Name :");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));

        jTextField3.setBackground(new java.awt.Color(53, 59, 72));
        jTextField3.setFont(new java.awt.Font("Aharoni", 0, 12)); // NOI18N
        jTextField3.setForeground(new java.awt.Color(204, 204, 255));
        jTextField3.setText("Enter your father's name");
        jTextField3.setBorder(null);
        jTextField3.setCaretColor(new java.awt.Color(255, 255, 255));
        jTextField3.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        jTextField3.setOpaque(false);
        jTextField3.setSelectionColor(new java.awt.Color(255, 255, 255));
        jTextField3.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField3FocusGained(evt);
            }
        });
        jPanel1.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 290, 20));

        jSeparator6.setForeground(new java.awt.Color(255, 204, 102));
        jPanel1.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 310, 20));

        jLabel13.setFont(new java.awt.Font("Book Antiqua", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Mother's Name :");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, -1, -1));

        jTextField5.setBackground(new java.awt.Color(53, 59, 72));
        jTextField5.setFont(new java.awt.Font("Aharoni", 0, 12)); // NOI18N
        jTextField5.setForeground(new java.awt.Color(204, 204, 255));
        jTextField5.setText("Enter your mother\"s name");
        jTextField5.setBorder(null);
        jTextField5.setCaretColor(new java.awt.Color(255, 255, 255));
        jTextField5.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        jTextField5.setOpaque(false);
        jTextField5.setSelectionColor(new java.awt.Color(255, 255, 255));
        jTextField5.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField5FocusGained(evt);
            }
        });
        jPanel1.add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 290, 30));

        jSeparator4.setForeground(new java.awt.Color(255, 204, 102));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 290, 20));

        jLabel6.setFont(new java.awt.Font("Book Antiqua", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("NID  :");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, -1, -1));

        jTextField4.setBackground(new java.awt.Color(53, 59, 72));
        jTextField4.setFont(new java.awt.Font("Aharoni", 0, 12)); // NOI18N
        jTextField4.setForeground(new java.awt.Color(204, 204, 255));
        jTextField4.setText("Enter your national identity number");
        jTextField4.setBorder(null);
        jTextField4.setCaretColor(new java.awt.Color(255, 255, 255));
        jTextField4.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        jTextField4.setOpaque(false);
        jTextField4.setSelectionColor(new java.awt.Color(255, 255, 255));
        jTextField4.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField4FocusGained(evt);
            }
        });
        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, 240, 20));

        jSeparator2.setForeground(new java.awt.Color(255, 204, 102));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 290, 20));

        jRadioButton1.setBackground(new java.awt.Color(53, 59, 72));
        jRadioButton1.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton1.setText("If Not");
        jPanel1.add(jRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 200, -1, -1));

        jLabel10.setFont(new java.awt.Font("Book Antiqua", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Date of Birth :");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, -1, -1));
        jPanel1.add(jDateChooser2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 230, 120, 30));

        jCheckBox3.setBackground(new java.awt.Color(53, 59, 72));
        jCheckBox3.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBox3.setText("Male");
        jCheckBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox3ActionPerformed(evt);
            }
        });
        jPanel1.add(jCheckBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 233, -1, 20));

        jCheckBox5.setBackground(new java.awt.Color(53, 59, 72));
        jCheckBox5.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBox5.setText("Female");
        jCheckBox5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox5ActionPerformed(evt);
            }
        });
        jPanel1.add(jCheckBox5, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 233, 70, 20));

        jCheckBox6.setBackground(new java.awt.Color(53, 59, 72));
        jCheckBox6.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBox6.setText("Others");
        jCheckBox6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox6ActionPerformed(evt);
            }
        });
        jPanel1.add(jCheckBox6, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 233, 70, 20));

        jLabel8.setFont(new java.awt.Font("Book Antiqua", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Present Address :");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, -1, -1));

        jTextArea5.setBackground(new java.awt.Color(53, 59, 72));
        jTextArea5.setColumns(20);
        jTextArea5.setForeground(new java.awt.Color(255, 255, 255));
        jTextArea5.setRows(5);
        jScrollPane4.setViewportView(jTextArea5);

        jPanel1.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 270, 270, 50));

        jLabel15.setFont(new java.awt.Font("Book Antiqua", 0, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Permanent Address :");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, -1, -1));

        jTextArea4.setBackground(new java.awt.Color(53, 59, 72));
        jTextArea4.setColumns(20);
        jTextArea4.setForeground(new java.awt.Color(255, 255, 255));
        jTextArea4.setRows(5);
        jScrollPane3.setViewportView(jTextArea4);

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 340, 270, 50));

        jLabel4.setForeground(new java.awt.Color(255, 51, 51));
        jLabel4.setText("Upload your Image");
        jLabel4.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jLabel4FocusGained(evt);
            }
        });
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 100, -1, -1));

        jButton4.setBackground(new java.awt.Color(53, 59, 72));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hello_bangladesh/person-icon.png"))); // NOI18N
        jButton4.setBorder(null);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 40, 120, 140));

        jLabel3.setForeground(new java.awt.Color(255, 51, 51));
        jLabel3.setText("Upload your sign");
        jLabel3.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jLabel3FocusGained(evt);
            }
        });
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 100, -1, -1));

        jButton1.setBackground(new java.awt.Color(53, 59, 72));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hello_bangladesh/oYPS__file_document_to_sign_signature_signed_sign_sheet_contract_paper_page_text-512.png"))); // NOI18N
        jButton1.setBorder(null);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 40, 120, 140));

        jLabel16.setFont(new java.awt.Font("Book Antiqua", 0, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Birth Certificate no  :");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 200, -1, -1));

        jTextField6.setBackground(new java.awt.Color(53, 59, 72));
        jTextField6.setFont(new java.awt.Font("Aharoni", 0, 12)); // NOI18N
        jTextField6.setForeground(new java.awt.Color(204, 204, 255));
        jTextField6.setText("your birth certificate no");
        jTextField6.setBorder(null);
        jTextField6.setCaretColor(new java.awt.Color(255, 255, 255));
        jTextField6.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        jTextField6.setOpaque(false);
        jTextField6.setSelectionColor(new java.awt.Color(255, 255, 255));
        jTextField6.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField6FocusGained(evt);
            }
        });
        jTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField6ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 200, 160, 20));

        jSeparator3.setForeground(new java.awt.Color(255, 204, 102));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 220, 290, 20));

        jLabel17.setFont(new java.awt.Font("Book Antiqua", 0, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Passport no :");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 230, -1, -1));

        jTextField8.setBackground(new java.awt.Color(53, 59, 72));
        jTextField8.setFont(new java.awt.Font("Aharoni", 0, 12)); // NOI18N
        jTextField8.setForeground(new java.awt.Color(204, 204, 255));
        jTextField8.setText("your passport no");
        jTextField8.setBorder(null);
        jTextField8.setCaretColor(new java.awt.Color(255, 255, 255));
        jTextField8.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        jTextField8.setOpaque(false);
        jTextField8.setSelectionColor(new java.awt.Color(255, 255, 255));
        jTextField8.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField8FocusGained(evt);
            }
        });
        jTextField8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField8ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 230, 150, 20));

        jSeparator7.setForeground(new java.awt.Color(255, 204, 102));
        jSeparator7.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jSeparator7FocusGained(evt);
            }
        });
        jPanel1.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 250, 310, 20));

        jLabel18.setFont(new java.awt.Font("Book Antiqua", 0, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("TIN  :");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 260, -1, -1));

        jTextField9.setBackground(new java.awt.Color(53, 59, 72));
        jTextField9.setFont(new java.awt.Font("Aharoni", 0, 12)); // NOI18N
        jTextField9.setForeground(new java.awt.Color(204, 204, 255));
        jTextField9.setText("Taxpayer identification number");
        jTextField9.setBorder(null);
        jTextField9.setCaretColor(new java.awt.Color(255, 255, 255));
        jTextField9.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        jTextField9.setOpaque(false);
        jTextField9.setSelectionColor(new java.awt.Color(255, 255, 255));
        jTextField9.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField9FocusGained(evt);
            }
        });
        jTextField9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField9ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField9, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 260, 180, 20));

        jSeparator8.setForeground(new java.awt.Color(255, 204, 102));
        jPanel1.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 280, 320, 20));

        jLabel12.setFont(new java.awt.Font("Book Antiqua", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Mobile no :");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 290, -1, -1));

        jTextField7.setBackground(new java.awt.Color(53, 59, 72));
        jTextField7.setFont(new java.awt.Font("Aharoni", 0, 12)); // NOI18N
        jTextField7.setForeground(new java.awt.Color(255, 51, 51));
        jTextField7.setText("*A OTP code will be sent.");
        jTextField7.setBorder(null);
        jTextField7.setCaretColor(new java.awt.Color(255, 255, 255));
        jTextField7.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        jTextField7.setOpaque(false);
        jTextField7.setSelectionColor(new java.awt.Color(255, 255, 255));
        jTextField7.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField7FocusGained(evt);
            }
        });
        jTextField7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField7ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 290, 160, 20));

        jButton3.setBackground(new java.awt.Color(53, 59, 72));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hello_bangladesh/sign-up-button-png-28490.png"))); // NOI18N
        jButton3.setBorder(null);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 400, 60, 20));

        jButton2.setBackground(new java.awt.Color(53, 59, 72));
        jButton2.setForeground(new java.awt.Color(53, 59, 72));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hello_bangladesh/login-button-png-18022.png"))); // NOI18N
        jButton2.setBorder(null);
        jButton2.setBorderPainted(false);
        jButton2.setFocusTraversalPolicyProvider(true);
        jButton2.setFocusable(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 0, 80, 30));

        jSeparator9.setForeground(new java.awt.Color(255, 204, 102));
        jPanel1.add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 310, 310, 20));

        jLabel2.setFont(new java.awt.Font("Book Antiqua", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Password :");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 320, -1, -1));

        jPasswordField1.setBackground(new java.awt.Color(53, 59, 72));
        jPasswordField1.setForeground(new java.awt.Color(204, 204, 255));
        jPasswordField1.setText("Enter your password");
        jPasswordField1.setBorder(null);
        jPasswordField1.setOpaque(false);
        jPasswordField1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jPasswordField1FocusGained(evt);
            }
        });
        jPasswordField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField1ActionPerformed(evt);
            }
        });
        jPanel1.add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 340, 290, -1));

        jSeparator10.setForeground(new java.awt.Color(255, 204, 102));
        jPanel1.add(jSeparator10, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 360, 290, 20));

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("maximize");
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 10, 40, -1));

        jLabeMin.setFont(new java.awt.Font("Adobe Devanagari", 1, 24)); // NOI18N
        jLabeMin.setForeground(new java.awt.Color(255, 255, 102));
        jLabeMin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hello_bangladesh/image/minimize.png"))); // NOI18N
        jLabeMin.setToolTipText("");
        jLabeMin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabeMinMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabeMinMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabeMinMouseExited(evt);
            }
        });
        jPanel1.add(jLabeMin, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 10, -1, 20));

        jLabelClose.setFont(new java.awt.Font("Adobe Devanagari", 0, 18)); // NOI18N
        jLabelClose.setForeground(new java.awt.Color(255, 0, 0));
        jLabelClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hello_bangladesh/image/close.png"))); // NOI18N
        jLabelClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelCloseMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelCloseMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelCloseMouseExited(evt);
            }
        });
        jPanel1.add(jLabelClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 10, 20, 20));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 450));

        bangladesh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hello_bangladesh/image/bangladesh map_316px.png"))); // NOI18N
        getContentPane().add(bangladesh, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField2FocusGained
        jTextField2.setText("");
    }//GEN-LAST:event_jTextField2FocusGained

    private void jTextField3FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField3FocusGained
        jTextField3.setText("");
    }//GEN-LAST:event_jTextField3FocusGained

    private void jTextField4FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField4FocusGained
        jTextField4.setText("");
    }//GEN-LAST:event_jTextField4FocusGained

    private void jTextField5FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField5FocusGained
        jTextField5.setText("");
    }//GEN-LAST:event_jTextField5FocusGained

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jCheckBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox3ActionPerformed
        // TODO add your handling code here:
        if(jCheckBox3.isSelected())
        {
            jCheckBox5.setSelected(false);
            jCheckBox6.setSelected(false);
            Gender="Male";
        }
    }//GEN-LAST:event_jCheckBox3ActionPerformed

    private void jCheckBox5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox5ActionPerformed
        // TODO add your handling code here:
        if(jCheckBox5.isSelected())
        {
            jCheckBox3.setSelected(false);
            jCheckBox6.setSelected(false);
            Gender="Female";
        }
    }//GEN-LAST:event_jCheckBox5ActionPerformed

    private void jCheckBox6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox6ActionPerformed
        // TODO add your handling code here:
        if(jCheckBox6.isSelected())
        {
            jCheckBox3.setSelected(false);
            jCheckBox5.setSelected(false);
            Gender="Others";

        }
    }//GEN-LAST:event_jCheckBox6ActionPerformed

    private void jTextField7FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField7FocusGained
          jTextField7.setText("");
    }//GEN-LAST:event_jTextField7FocusGained

    private void jTextField7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField7ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
           boolean check=true;
           String Name=jTextField2.getText();
           String FathersName=jTextField3.getText();
           String MothersName=jTextField5.getText();
           String NID=jTextField4.getText();
           login.USERID=NID;
           Date date = jDateChooser2. getDate();
           String DateOfBirth=DateFormat.getDateInstance().format(date);
           String PresentAddress=jTextArea5.getText();
           String PermanentAddress=jTextArea4.getText();
           String BirthCertificateNo=jTextField6.getText();
           String PassportNo=jTextField8.getText();
           String TIN=jTextField9.getText();
          String Password=new String(jPasswordField1.getPassword());
           String MobileNo=jTextField7.getText();
           if(Name.isEmpty() || FathersName.isEmpty() || MothersName.isEmpty() || DateOfBirth.isEmpty() || PresentAddress.isEmpty() || PermanentAddress.isEmpty() || PassportNo.isEmpty())
           {
               JOptionPane.showMessageDialog(null,"Fields are Empty");
               
                check=false;
           }
           if(!containsNumber(NID))
           {
               JOptionPane.showMessageDialog(null,"NID is Invalid");
               check=false;
           }
            if(!containsNumber(TIN))
            {
                JOptionPane.showMessageDialog(null,"TIN is Invalid");
                check=false;
            }
           
            if(check){
          
           //FileOperation fo=new FileOperation(Name,FathersName,MothersName,NID,PresentAddress,PermanentAddress,BirthCertificateNo,TIN,PassportNo,MobileNo);
           ///fo.writeInfoToFile(NID, password);
           try{
           DatabaseOperation operation1=new DatabaseOperation();
           operation1.connect();
           operation1.setData(Name,FathersName,MothersName,NID,PresentAddress,PermanentAddress,Gender,DateOfBirth,TIN,MobileNo,PassportNo,Password);
           //io.saveImage(fo.fp.getAbsolutePath());
           try{
           operation1.insertImage(image1,image2,NID, Name);
            }
           catch(Exception e)
           {
               check=false;
               JOptionPane.showMessageDialog(null,e.toString());
           }
           operation1.getSavedImages();
            }
           catch(Exception e)
           {
               check=false;
               JOptionPane.showMessageDialog(null,e.toString());
           }
           if(check)
           {
           otp otp = new otp();
           otp.setVisible(true);
           this.dispose();
           }
           }
         
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTextField6FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField6FocusGained
          jTextField6.setText("");
    }//GEN-LAST:event_jTextField6FocusGained

    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField6ActionPerformed

    private void jTextField8FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField8FocusGained
          jTextField8.setText("");
    }//GEN-LAST:event_jTextField8FocusGained

    private void jTextField8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField8ActionPerformed

    private void jTextField9FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField9FocusGained
          jTextField9.setText("");
    }//GEN-LAST:event_jTextField9FocusGained

    private void jTextField9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField9ActionPerformed

    private void jSeparator7FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jSeparator7FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_jSeparator7FocusGained

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        dispose();
        login login = new login();
        login.setVisible(true);
      
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jLabel4FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jLabel4FocusGained
        jLabel8.setText("Upload your image");
    }//GEN-LAST:event_jLabel4FocusGained

    private void jLabel3FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jLabel3FocusGained
        jLabel3.setText("Upload your sign");
    }//GEN-LAST:event_jLabel3FocusGained

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        image1=io.selectImage();
        jButton4.setIcon(io.ii);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jPasswordField1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPasswordField1FocusGained
        jPasswordField1.setText("");
    }//GEN-LAST:event_jPasswordField1FocusGained

    private void jPasswordField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField1ActionPerformed

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        if(maximized)
        {
            //handle fullscreen - taskbar
            this.setExtendedState(JFrame.MAXIMIZED_BOTH);  
            GraphicsEnvironment env = GraphicsEnvironment.getLocalGraphicsEnvironment();  
            this.setMaximizedBounds(env.getMaximumWindowBounds());
            maximized = false;
         }
        else
        {
            
            setExtendedState(JFrame.NORMAL);
            maximized = true;
        }
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jLabeMinMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabeMinMouseClicked
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_jLabeMinMouseClicked

    private void jLabeMinMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabeMinMouseEntered
        ii = new ImageIcon(getClass().getResource("image\\minimize1.png"));
        jLabeMin.setIcon(ii);
    }//GEN-LAST:event_jLabeMinMouseEntered

    private void jLabeMinMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabeMinMouseExited
        ii = new ImageIcon(getClass().getResource("image\\minimize.png"));
        jLabeMin.setIcon(ii);
    }//GEN-LAST:event_jLabeMinMouseExited

    private void jLabelCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelCloseMouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabelCloseMouseClicked

    private void jLabelCloseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelCloseMouseEntered
        ii = new ImageIcon(getClass().getResource("image\\close1.png"));
        jLabelClose.setIcon(ii);
    }//GEN-LAST:event_jLabelCloseMouseEntered

    private void jLabelCloseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelCloseMouseExited
        ii = new ImageIcon(getClass().getResource("image\\close.png"));
        jLabelClose.setIcon(ii);
    }//GEN-LAST:event_jLabelCloseMouseExited

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        image2=io.selectImage();
        jButton1.setIcon(io.ii);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new signup().setVisible(true);
            }
        });
    }
boolean containsNumber(String s)
{
     for(int i=0;i<s.length();i++)
           {
              
               if(s.codePointAt(i)>57)
                   return false;
           }
     return true;
}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bangladesh;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox5;
    private javax.swing.JCheckBox jCheckBox6;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private javax.swing.JLabel jLabeMin;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelClose;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JTextArea jTextArea4;
    private javax.swing.JTextArea jTextArea5;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
